[2024-08-04 00:18:40,894] {scheduler_job.py:182} INFO - Started process (PID=20523) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 00:18:40,896] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 00:18:40,899] {logging_mixin.py:104} INFO - [2024-08-04 00:18:40,899] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 00:18:40,912] {logging_mixin.py:104} INFO - [2024-08-04 00:18:40,910] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 00:18:40,913] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 00:18:40,989] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.101 seconds
[2024-08-04 00:35:02,243] {scheduler_job.py:182} INFO - Started process (PID=20552) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 00:35:02,244] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 00:35:02,245] {logging_mixin.py:104} INFO - [2024-08-04 00:35:02,245] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 00:35:02,256] {logging_mixin.py:104} INFO - [2024-08-04 00:35:02,255] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 00:35:02,256] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 00:35:02,358] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.117 seconds
[2024-08-04 01:19:38,499] {scheduler_job.py:182} INFO - Started process (PID=20581) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 01:19:38,501] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 01:19:38,501] {logging_mixin.py:104} INFO - [2024-08-04 01:19:38,501] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 01:19:38,516] {logging_mixin.py:104} INFO - [2024-08-04 01:19:38,515] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 01:19:38,516] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 01:19:38,579] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-04 01:35:22,742] {scheduler_job.py:182} INFO - Started process (PID=20610) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 01:35:22,743] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 01:35:22,743] {logging_mixin.py:104} INFO - [2024-08-04 01:35:22,743] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 01:35:22,753] {logging_mixin.py:104} INFO - [2024-08-04 01:35:22,752] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 01:35:22,753] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 01:35:22,837] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.097 seconds
[2024-08-04 02:07:08,120] {scheduler_job.py:182} INFO - Started process (PID=20639) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:07:08,121] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 02:07:08,122] {logging_mixin.py:104} INFO - [2024-08-04 02:07:08,122] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:07:08,130] {logging_mixin.py:104} INFO - [2024-08-04 02:07:08,129] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 02:07:08,130] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:07:08,190] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 02:20:23,127] {scheduler_job.py:182} INFO - Started process (PID=20668) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:20:23,127] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 02:20:23,128] {logging_mixin.py:104} INFO - [2024-08-04 02:20:23,128] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:20:23,140] {logging_mixin.py:104} INFO - [2024-08-04 02:20:23,138] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 02:20:23,141] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:20:23,214] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.089 seconds
[2024-08-04 02:20:54,457] {scheduler_job.py:182} INFO - Started process (PID=20705) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:20:54,458] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 02:20:54,458] {logging_mixin.py:104} INFO - [2024-08-04 02:20:54,458] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:20:54,466] {logging_mixin.py:104} INFO - [2024-08-04 02:20:54,465] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 02:20:54,466] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:20:54,527] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-04 02:42:57,401] {scheduler_job.py:182} INFO - Started process (PID=20726) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:42:57,402] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 02:42:57,402] {logging_mixin.py:104} INFO - [2024-08-04 02:42:57,402] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:42:57,410] {logging_mixin.py:104} INFO - [2024-08-04 02:42:57,409] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 02:42:57,411] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:42:57,471] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 02:43:28,652] {scheduler_job.py:182} INFO - Started process (PID=20763) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:43:28,653] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 02:43:28,653] {logging_mixin.py:104} INFO - [2024-08-04 02:43:28,653] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:43:28,662] {logging_mixin.py:104} INFO - [2024-08-04 02:43:28,661] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 02:43:28,662] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 02:43:28,724] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 03:21:32,717] {scheduler_job.py:182} INFO - Started process (PID=20784) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 03:21:32,720] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 03:21:32,721] {logging_mixin.py:104} INFO - [2024-08-04 03:21:32,721] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 03:21:32,729] {logging_mixin.py:104} INFO - [2024-08-04 03:21:32,728] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 03:21:32,729] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 03:21:32,802] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.087 seconds
[2024-08-04 03:22:04,049] {scheduler_job.py:182} INFO - Started process (PID=20821) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 03:22:04,050] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 03:22:04,050] {logging_mixin.py:104} INFO - [2024-08-04 03:22:04,050] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 03:22:04,060] {logging_mixin.py:104} INFO - [2024-08-04 03:22:04,059] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 03:22:04,062] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 03:22:04,122] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 04:22:28,535] {scheduler_job.py:182} INFO - Started process (PID=20842) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 04:22:28,536] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 04:22:28,536] {logging_mixin.py:104} INFO - [2024-08-04 04:22:28,536] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 04:22:28,545] {logging_mixin.py:104} INFO - [2024-08-04 04:22:28,544] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 04:22:28,546] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 04:22:28,608] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 04:22:59,987] {scheduler_job.py:182} INFO - Started process (PID=20879) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 04:22:59,988] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 04:22:59,989] {logging_mixin.py:104} INFO - [2024-08-04 04:22:59,989] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 04:23:00,001] {logging_mixin.py:104} INFO - [2024-08-04 04:23:00,000] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 04:23:00,005] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 04:23:00,067] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-04 05:00:31,258] {scheduler_job.py:182} INFO - Started process (PID=20900) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:00:31,258] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 05:00:31,259] {logging_mixin.py:104} INFO - [2024-08-04 05:00:31,259] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:00:31,267] {logging_mixin.py:104} INFO - [2024-08-04 05:00:31,266] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 05:00:31,269] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:00:31,330] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 05:01:02,588] {scheduler_job.py:182} INFO - Started process (PID=20937) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:01:02,590] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 05:01:02,590] {logging_mixin.py:104} INFO - [2024-08-04 05:01:02,590] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:01:02,599] {logging_mixin.py:104} INFO - [2024-08-04 05:01:02,598] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 05:01:02,600] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:01:02,661] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-04 05:09:54,983] {scheduler_job.py:182} INFO - Started process (PID=20958) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:09:54,984] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 05:09:54,984] {logging_mixin.py:104} INFO - [2024-08-04 05:09:54,984] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:09:54,993] {logging_mixin.py:104} INFO - [2024-08-04 05:09:54,992] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 05:09:54,995] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:09:55,055] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 05:23:26,674] {scheduler_job.py:182} INFO - Started process (PID=20987) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:23:26,675] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 05:23:26,675] {logging_mixin.py:104} INFO - [2024-08-04 05:23:26,675] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:23:26,685] {logging_mixin.py:104} INFO - [2024-08-04 05:23:26,683] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 05:23:26,686] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:23:26,751] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-04 05:23:57,467] {scheduler_job.py:182} INFO - Started process (PID=21015) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:23:57,468] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 05:23:57,469] {logging_mixin.py:104} INFO - [2024-08-04 05:23:57,469] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:23:57,477] {logging_mixin.py:104} INFO - [2024-08-04 05:23:57,476] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 05:23:57,478] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:23:57,539] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 05:24:57,692] {scheduler_job.py:182} INFO - Started process (PID=21045) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:24:57,693] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 05:24:57,693] {logging_mixin.py:104} INFO - [2024-08-04 05:24:57,693] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:24:57,702] {logging_mixin.py:104} INFO - [2024-08-04 05:24:57,701] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 05:24:57,703] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:24:57,764] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 05:41:50,201] {scheduler_job.py:182} INFO - Started process (PID=21074) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:41:50,202] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 05:41:50,202] {logging_mixin.py:104} INFO - [2024-08-04 05:41:50,202] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:41:50,211] {logging_mixin.py:104} INFO - [2024-08-04 05:41:50,210] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 05:41:50,212] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 05:41:50,291] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.092 seconds
[2024-08-04 06:24:36,382] {scheduler_job.py:182} INFO - Started process (PID=21103) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:24:36,385] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 06:24:36,387] {logging_mixin.py:104} INFO - [2024-08-04 06:24:36,387] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:24:36,395] {logging_mixin.py:104} INFO - [2024-08-04 06:24:36,394] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 06:24:36,396] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:24:36,459] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-04 06:25:06,498] {scheduler_job.py:182} INFO - Started process (PID=21131) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:25:06,499] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 06:25:06,500] {logging_mixin.py:104} INFO - [2024-08-04 06:25:06,500] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:25:06,507] {logging_mixin.py:104} INFO - [2024-08-04 06:25:06,506] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 06:25:06,511] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:25:06,574] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-04 06:43:03,675] {scheduler_job.py:182} INFO - Started process (PID=21161) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:43:03,676] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 06:43:03,679] {logging_mixin.py:104} INFO - [2024-08-04 06:43:03,679] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:43:03,691] {logging_mixin.py:104} INFO - [2024-08-04 06:43:03,688] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 06:43:03,691] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 06:43:03,754] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-04 07:14:38,552] {scheduler_job.py:182} INFO - Started process (PID=21190) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:14:38,553] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 07:14:38,554] {logging_mixin.py:104} INFO - [2024-08-04 07:14:38,554] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:14:38,566] {logging_mixin.py:104} INFO - [2024-08-04 07:14:38,565] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 07:14:38,567] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:14:38,634] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2024-08-04 07:25:46,193] {scheduler_job.py:182} INFO - Started process (PID=21219) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:25:46,194] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 07:25:46,194] {logging_mixin.py:104} INFO - [2024-08-04 07:25:46,194] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:25:46,205] {logging_mixin.py:104} INFO - [2024-08-04 07:25:46,204] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 07:25:46,206] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:25:46,285] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.095 seconds
[2024-08-04 07:58:46,165] {scheduler_job.py:182} INFO - Started process (PID=21248) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:58:46,166] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 07:58:46,167] {logging_mixin.py:104} INFO - [2024-08-04 07:58:46,167] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:58:46,180] {logging_mixin.py:104} INFO - [2024-08-04 07:58:46,179] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 07:58:46,181] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 07:58:46,256] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.093 seconds
[2024-08-04 08:26:42,413] {scheduler_job.py:182} INFO - Started process (PID=21277) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 08:26:42,414] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 08:26:42,414] {logging_mixin.py:104} INFO - [2024-08-04 08:26:42,414] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 08:26:42,424] {logging_mixin.py:104} INFO - [2024-08-04 08:26:42,423] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 08:26:42,424] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 08:26:42,487] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 08:58:33,191] {scheduler_job.py:182} INFO - Started process (PID=21306) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 08:58:33,197] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 08:58:33,197] {logging_mixin.py:104} INFO - [2024-08-04 08:58:33,197] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 08:58:33,220] {logging_mixin.py:104} INFO - [2024-08-04 08:58:33,218] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 08:58:33,221] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 08:58:33,284] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.095 seconds
[2024-08-04 09:22:36,779] {scheduler_job.py:182} INFO - Started process (PID=21335) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:22:36,780] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 09:22:36,781] {logging_mixin.py:104} INFO - [2024-08-04 09:22:36,780] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:22:36,790] {logging_mixin.py:104} INFO - [2024-08-04 09:22:36,789] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 09:22:36,791] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:22:36,865] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.088 seconds
[2024-08-04 09:27:21,452] {scheduler_job.py:182} INFO - Started process (PID=21364) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:27:21,457] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 09:27:21,458] {logging_mixin.py:104} INFO - [2024-08-04 09:27:21,458] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:27:21,479] {logging_mixin.py:104} INFO - [2024-08-04 09:27:21,475] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 09:27:21,480] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:27:21,550] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.100 seconds
[2024-08-04 09:27:52,719] {scheduler_job.py:182} INFO - Started process (PID=21401) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:27:52,719] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 09:27:52,720] {logging_mixin.py:104} INFO - [2024-08-04 09:27:52,720] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:27:52,728] {logging_mixin.py:104} INFO - [2024-08-04 09:27:52,727] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 09:27:52,729] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:27:52,789] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 09:42:44,764] {scheduler_job.py:182} INFO - Started process (PID=21422) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:42:44,765] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 09:42:44,765] {logging_mixin.py:104} INFO - [2024-08-04 09:42:44,765] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:42:44,777] {logging_mixin.py:104} INFO - [2024-08-04 09:42:44,776] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 09:42:44,778] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:42:44,847] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2024-08-04 09:43:15,617] {scheduler_job.py:182} INFO - Started process (PID=21456) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:43:15,618] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 09:43:15,618] {logging_mixin.py:104} INFO - [2024-08-04 09:43:15,618] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:43:15,626] {logging_mixin.py:104} INFO - [2024-08-04 09:43:15,626] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 09:43:15,627] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 09:43:15,691] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 10:20:04,963] {scheduler_job.py:182} INFO - Started process (PID=21480) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:20:04,963] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 10:20:04,964] {logging_mixin.py:104} INFO - [2024-08-04 10:20:04,964] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:20:04,974] {logging_mixin.py:104} INFO - [2024-08-04 10:20:04,973] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 10:20:04,974] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:20:05,042] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-04 10:28:19,913] {scheduler_job.py:182} INFO - Started process (PID=21509) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:28:19,914] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 10:28:19,914] {logging_mixin.py:104} INFO - [2024-08-04 10:28:19,914] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:28:19,922] {logging_mixin.py:104} INFO - [2024-08-04 10:28:19,921] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 10:28:19,923] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:28:19,984] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 10:28:51,174] {scheduler_job.py:182} INFO - Started process (PID=21546) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:28:51,174] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 10:28:51,175] {logging_mixin.py:104} INFO - [2024-08-04 10:28:51,175] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:28:51,183] {logging_mixin.py:104} INFO - [2024-08-04 10:28:51,182] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 10:28:51,183] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:28:51,243] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-04 10:32:10,219] {scheduler_job.py:182} INFO - Started process (PID=21567) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:32:10,221] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 10:32:10,222] {logging_mixin.py:104} INFO - [2024-08-04 10:32:10,221] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:32:10,233] {logging_mixin.py:104} INFO - [2024-08-04 10:32:10,232] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 10:32:10,234] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:32:10,314] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.097 seconds
[2024-08-04 10:32:41,431] {scheduler_job.py:182} INFO - Started process (PID=21604) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:32:41,431] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 10:32:41,432] {logging_mixin.py:104} INFO - [2024-08-04 10:32:41,432] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:32:41,440] {logging_mixin.py:104} INFO - [2024-08-04 10:32:41,439] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 10:32:41,442] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 10:32:41,503] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-04 11:08:10,095] {scheduler_job.py:182} INFO - Started process (PID=21625) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:08:10,095] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:08:10,096] {logging_mixin.py:104} INFO - [2024-08-04 11:08:10,096] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:08:10,114] {logging_mixin.py:104} INFO - [2024-08-04 11:08:10,111] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:08:10,115] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:08:10,187] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.101 seconds
[2024-08-04 11:08:41,854] {scheduler_job.py:182} INFO - Started process (PID=21662) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:08:41,856] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:08:41,856] {logging_mixin.py:104} INFO - [2024-08-04 11:08:41,856] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:08:41,863] {logging_mixin.py:104} INFO - [2024-08-04 11:08:41,862] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:08:41,864] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:08:41,922] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.070 seconds
[2024-08-04 11:09:12,987] {scheduler_job.py:182} INFO - Started process (PID=21691) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:09:12,987] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:09:12,988] {logging_mixin.py:104} INFO - [2024-08-04 11:09:12,988] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:09:12,996] {logging_mixin.py:104} INFO - [2024-08-04 11:09:12,995] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:09:12,996] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:09:13,057] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 11:09:45,892] {scheduler_job.py:182} INFO - Started process (PID=21712) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:09:45,893] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:09:45,893] {logging_mixin.py:104} INFO - [2024-08-04 11:09:45,893] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:09:45,906] {logging_mixin.py:104} INFO - [2024-08-04 11:09:45,905] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:09:45,910] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:09:45,970] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-04 11:10:17,167] {scheduler_job.py:182} INFO - Started process (PID=21749) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:10:17,168] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:10:17,168] {logging_mixin.py:104} INFO - [2024-08-04 11:10:17,168] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:10:17,178] {logging_mixin.py:104} INFO - [2024-08-04 11:10:17,177] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:10:17,179] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:10:17,240] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 11:29:38,230] {scheduler_job.py:182} INFO - Started process (PID=21770) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:29:38,231] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:29:38,231] {logging_mixin.py:104} INFO - [2024-08-04 11:29:38,231] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:29:38,241] {logging_mixin.py:104} INFO - [2024-08-04 11:29:38,240] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:29:38,242] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:29:38,308] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-04 11:46:05,530] {scheduler_job.py:182} INFO - Started process (PID=21799) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:46:05,531] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:46:05,531] {logging_mixin.py:104} INFO - [2024-08-04 11:46:05,531] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:46:05,541] {logging_mixin.py:104} INFO - [2024-08-04 11:46:05,540] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:46:05,542] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:46:05,607] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-04 11:46:36,875] {scheduler_job.py:182} INFO - Started process (PID=21836) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:46:36,876] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 11:46:36,878] {logging_mixin.py:104} INFO - [2024-08-04 11:46:36,878] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:46:36,887] {logging_mixin.py:104} INFO - [2024-08-04 11:46:36,885] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 11:46:36,888] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 11:46:36,948] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-04 12:30:22,675] {scheduler_job.py:182} INFO - Started process (PID=21857) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 12:30:22,676] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 12:30:22,677] {logging_mixin.py:104} INFO - [2024-08-04 12:30:22,677] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 12:30:22,688] {logging_mixin.py:104} INFO - [2024-08-04 12:30:22,687] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 12:30:22,689] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 12:30:22,769] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.095 seconds
[2024-08-04 12:30:52,846] {scheduler_job.py:182} INFO - Started process (PID=21885) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 12:30:52,847] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 12:30:52,847] {logging_mixin.py:104} INFO - [2024-08-04 12:30:52,847] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 12:30:52,855] {logging_mixin.py:104} INFO - [2024-08-04 12:30:52,854] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 12:30:52,856] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 12:30:52,916] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 13:19:18,222] {scheduler_job.py:182} INFO - Started process (PID=21915) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 13:19:18,223] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 13:19:18,224] {logging_mixin.py:104} INFO - [2024-08-04 13:19:18,224] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 13:19:18,235] {logging_mixin.py:104} INFO - [2024-08-04 13:19:18,234] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 13:19:18,236] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 13:19:18,306] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.086 seconds
[2024-08-04 13:31:49,737] {scheduler_job.py:182} INFO - Started process (PID=21944) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 13:31:49,738] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 13:31:49,739] {logging_mixin.py:104} INFO - [2024-08-04 13:31:49,739] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 13:31:49,748] {logging_mixin.py:104} INFO - [2024-08-04 13:31:49,747] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 13:31:49,749] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 13:31:49,812] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-04 14:20:27,308] {scheduler_job.py:182} INFO - Started process (PID=21973) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:20:27,309] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:20:27,309] {logging_mixin.py:104} INFO - [2024-08-04 14:20:27,309] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:20:27,322] {logging_mixin.py:104} INFO - [2024-08-04 14:20:27,318] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:20:27,322] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:20:27,387] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2024-08-04 14:25:25,529] {scheduler_job.py:182} INFO - Started process (PID=22002) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:25:25,529] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:25:25,530] {logging_mixin.py:104} INFO - [2024-08-04 14:25:25,530] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:25:25,538] {logging_mixin.py:104} INFO - [2024-08-04 14:25:25,537] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:25:25,539] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:25:25,603] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 14:27:41,685] {scheduler_job.py:182} INFO - Started process (PID=22031) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:27:41,686] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:27:41,686] {logging_mixin.py:104} INFO - [2024-08-04 14:27:41,686] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:27:41,696] {logging_mixin.py:104} INFO - [2024-08-04 14:27:41,695] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:27:41,698] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:27:41,759] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 14:28:12,880] {scheduler_job.py:182} INFO - Started process (PID=22068) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:28:12,880] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:28:12,881] {logging_mixin.py:104} INFO - [2024-08-04 14:28:12,881] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:28:12,889] {logging_mixin.py:104} INFO - [2024-08-04 14:28:12,888] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:28:12,890] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:28:12,950] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 14:32:41,674] {scheduler_job.py:182} INFO - Started process (PID=22089) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:32:41,674] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:32:41,675] {logging_mixin.py:104} INFO - [2024-08-04 14:32:41,675] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:32:41,686] {logging_mixin.py:104} INFO - [2024-08-04 14:32:41,685] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:32:41,687] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:32:41,769] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.097 seconds
[2024-08-04 14:40:25,659] {scheduler_job.py:182} INFO - Started process (PID=22118) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:40:25,659] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:40:25,660] {logging_mixin.py:104} INFO - [2024-08-04 14:40:25,660] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:40:25,670] {logging_mixin.py:104} INFO - [2024-08-04 14:40:25,669] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:40:25,671] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:40:25,735] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-04 14:40:56,998] {scheduler_job.py:182} INFO - Started process (PID=22155) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:40:56,999] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:40:56,999] {logging_mixin.py:104} INFO - [2024-08-04 14:40:56,999] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:40:57,008] {logging_mixin.py:104} INFO - [2024-08-04 14:40:57,006] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:40:57,009] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:40:57,069] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 14:55:35,583] {scheduler_job.py:182} INFO - Started process (PID=22176) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:55:35,584] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 14:55:35,584] {logging_mixin.py:104} INFO - [2024-08-04 14:55:35,584] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:55:35,591] {logging_mixin.py:104} INFO - [2024-08-04 14:55:35,590] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 14:55:35,593] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 14:55:35,656] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 15:05:08,824] {scheduler_job.py:182} INFO - Started process (PID=22205) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:05:08,825] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:05:08,825] {logging_mixin.py:104} INFO - [2024-08-04 15:05:08,825] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:05:08,835] {logging_mixin.py:104} INFO - [2024-08-04 15:05:08,834] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:05:08,835] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:05:08,916] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.093 seconds
[2024-08-04 15:05:40,237] {scheduler_job.py:182} INFO - Started process (PID=22242) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:05:40,238] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:05:40,241] {logging_mixin.py:104} INFO - [2024-08-04 15:05:40,241] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:05:40,250] {logging_mixin.py:104} INFO - [2024-08-04 15:05:40,249] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:05:40,251] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:05:40,313] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-04 15:06:10,902] {scheduler_job.py:182} INFO - Started process (PID=22270) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:06:10,902] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:06:10,903] {logging_mixin.py:104} INFO - [2024-08-04 15:06:10,903] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:06:10,911] {logging_mixin.py:104} INFO - [2024-08-04 15:06:10,910] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:06:10,911] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:06:10,973] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 15:06:41,747] {scheduler_job.py:182} INFO - Started process (PID=22299) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:06:41,748] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:06:41,748] {logging_mixin.py:104} INFO - [2024-08-04 15:06:41,748] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:06:41,756] {logging_mixin.py:104} INFO - [2024-08-04 15:06:41,755] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:06:41,757] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:06:41,817] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 15:07:12,561] {scheduler_job.py:182} INFO - Started process (PID=22328) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:07:12,562] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:07:12,562] {logging_mixin.py:104} INFO - [2024-08-04 15:07:12,562] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:07:12,570] {logging_mixin.py:104} INFO - [2024-08-04 15:07:12,569] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:07:12,570] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:07:12,630] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-04 15:07:43,407] {scheduler_job.py:182} INFO - Started process (PID=22356) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:07:43,410] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:07:43,410] {logging_mixin.py:104} INFO - [2024-08-04 15:07:43,410] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:07:43,419] {logging_mixin.py:104} INFO - [2024-08-04 15:07:43,418] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:07:43,420] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:07:43,482] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-04 15:08:14,550] {scheduler_job.py:182} INFO - Started process (PID=22387) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:08:14,551] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:08:14,552] {logging_mixin.py:104} INFO - [2024-08-04 15:08:14,552] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:08:14,561] {logging_mixin.py:104} INFO - [2024-08-04 15:08:14,560] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:08:14,561] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:08:14,629] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2024-08-04 15:08:45,392] {scheduler_job.py:182} INFO - Started process (PID=22416) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:08:45,393] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:08:45,394] {logging_mixin.py:104} INFO - [2024-08-04 15:08:45,394] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:08:45,406] {logging_mixin.py:104} INFO - [2024-08-04 15:08:45,402] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:08:45,406] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:08:45,471] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-04 15:09:16,490] {scheduler_job.py:182} INFO - Started process (PID=22445) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:09:16,491] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:09:16,492] {logging_mixin.py:104} INFO - [2024-08-04 15:09:16,491] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:09:16,501] {logging_mixin.py:104} INFO - [2024-08-04 15:09:16,500] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:09:16,502] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:09:16,563] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-04 15:09:47,372] {scheduler_job.py:182} INFO - Started process (PID=22474) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:09:47,374] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:09:47,374] {logging_mixin.py:104} INFO - [2024-08-04 15:09:47,374] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:09:47,382] {logging_mixin.py:104} INFO - [2024-08-04 15:09:47,381] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:09:47,383] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:09:47,443] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 15:10:18,164] {scheduler_job.py:182} INFO - Started process (PID=22502) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:10:18,164] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:10:18,165] {logging_mixin.py:104} INFO - [2024-08-04 15:10:18,165] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:10:18,174] {logging_mixin.py:104} INFO - [2024-08-04 15:10:18,173] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:10:18,175] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:10:18,239] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-04 15:10:49,060] {scheduler_job.py:182} INFO - Started process (PID=22532) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:10:49,061] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:10:49,061] {logging_mixin.py:104} INFO - [2024-08-04 15:10:49,061] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:10:49,072] {logging_mixin.py:104} INFO - [2024-08-04 15:10:49,069] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:10:49,072] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:10:49,134] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 15:11:19,801] {scheduler_job.py:182} INFO - Started process (PID=22561) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:11:19,802] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:11:19,802] {logging_mixin.py:104} INFO - [2024-08-04 15:11:19,802] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:11:19,811] {logging_mixin.py:104} INFO - [2024-08-04 15:11:19,809] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:11:19,811] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:11:19,872] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 15:11:50,381] {scheduler_job.py:182} INFO - Started process (PID=22584) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:11:50,382] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:11:50,383] {logging_mixin.py:104} INFO - [2024-08-04 15:11:50,383] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:11:50,391] {logging_mixin.py:104} INFO - [2024-08-04 15:11:50,390] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:11:50,392] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:11:50,454] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 15:46:23,831] {scheduler_job.py:182} INFO - Started process (PID=22611) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:46:23,832] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 15:46:23,833] {logging_mixin.py:104} INFO - [2024-08-04 15:46:23,832] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:46:23,842] {logging_mixin.py:104} INFO - [2024-08-04 15:46:23,841] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 15:46:23,842] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 15:46:23,905] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 17:09:22,435] {scheduler_job.py:182} INFO - Started process (PID=22640) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:09:22,436] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 17:09:22,437] {logging_mixin.py:104} INFO - [2024-08-04 17:09:22,437] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:09:22,448] {logging_mixin.py:104} INFO - [2024-08-04 17:09:22,445] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 17:09:22,449] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:09:22,511] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-04 17:09:54,924] {scheduler_job.py:182} INFO - Started process (PID=22669) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:09:54,925] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 17:09:54,927] {logging_mixin.py:104} INFO - [2024-08-04 17:09:54,927] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:09:54,935] {logging_mixin.py:104} INFO - [2024-08-04 17:09:54,934] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 17:09:54,935] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:09:54,995] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 17:13:05,885] {scheduler_job.py:182} INFO - Started process (PID=22698) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:13:05,886] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 17:13:05,886] {logging_mixin.py:104} INFO - [2024-08-04 17:13:05,886] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:13:05,896] {logging_mixin.py:104} INFO - [2024-08-04 17:13:05,894] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 17:13:05,897] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:13:05,978] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.096 seconds
[2024-08-04 17:13:36,739] {scheduler_job.py:182} INFO - Started process (PID=22726) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:13:36,740] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 17:13:36,740] {logging_mixin.py:104} INFO - [2024-08-04 17:13:36,740] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:13:36,748] {logging_mixin.py:104} INFO - [2024-08-04 17:13:36,747] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 17:13:36,749] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 17:13:36,810] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 18:06:51,671] {scheduler_job.py:182} INFO - Started process (PID=22756) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:06:51,672] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 18:06:51,672] {logging_mixin.py:104} INFO - [2024-08-04 18:06:51,672] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:06:51,683] {logging_mixin.py:104} INFO - [2024-08-04 18:06:51,682] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 18:06:51,683] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:06:51,749] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-04 18:07:21,771] {scheduler_job.py:182} INFO - Started process (PID=22784) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:07:21,772] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 18:07:21,772] {logging_mixin.py:104} INFO - [2024-08-04 18:07:21,772] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:07:21,780] {logging_mixin.py:104} INFO - [2024-08-04 18:07:21,779] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 18:07:21,781] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:07:21,838] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.069 seconds
[2024-08-04 18:14:15,979] {scheduler_job.py:182} INFO - Started process (PID=22814) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:14:15,979] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 18:14:15,980] {logging_mixin.py:104} INFO - [2024-08-04 18:14:15,980] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:14:15,988] {logging_mixin.py:104} INFO - [2024-08-04 18:14:15,987] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 18:14:15,989] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:14:16,063] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2024-08-04 18:32:29,359] {scheduler_job.py:182} INFO - Started process (PID=22843) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:32:29,360] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 18:32:29,360] {logging_mixin.py:104} INFO - [2024-08-04 18:32:29,360] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:32:29,368] {logging_mixin.py:104} INFO - [2024-08-04 18:32:29,367] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 18:32:29,369] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:32:29,431] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 18:33:15,749] {scheduler_job.py:182} INFO - Started process (PID=22872) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:33:15,749] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 18:33:15,750] {logging_mixin.py:104} INFO - [2024-08-04 18:33:15,750] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:33:15,761] {logging_mixin.py:104} INFO - [2024-08-04 18:33:15,758] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 18:33:15,762] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 18:33:15,824] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-04 19:14:55,046] {scheduler_job.py:182} INFO - Started process (PID=22901) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:14:55,047] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 19:14:55,047] {logging_mixin.py:104} INFO - [2024-08-04 19:14:55,047] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:14:55,055] {logging_mixin.py:104} INFO - [2024-08-04 19:14:55,054] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 19:14:55,055] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:14:55,119] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-04 19:15:26,279] {scheduler_job.py:182} INFO - Started process (PID=22937) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:15:26,279] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 19:15:26,280] {logging_mixin.py:104} INFO - [2024-08-04 19:15:26,280] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:15:26,288] {logging_mixin.py:104} INFO - [2024-08-04 19:15:26,287] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 19:15:26,288] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:15:26,350] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-04 19:34:50,699] {scheduler_job.py:182} INFO - Started process (PID=22959) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:34:50,700] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 19:34:50,700] {logging_mixin.py:104} INFO - [2024-08-04 19:34:50,700] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:34:50,708] {logging_mixin.py:104} INFO - [2024-08-04 19:34:50,707] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 19:34:50,709] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:34:50,771] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-04 19:35:22,008] {scheduler_job.py:182} INFO - Started process (PID=22996) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:35:22,010] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 19:35:22,011] {logging_mixin.py:104} INFO - [2024-08-04 19:35:22,011] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:35:22,019] {logging_mixin.py:104} INFO - [2024-08-04 19:35:22,018] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 19:35:22,019] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 19:35:22,079] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-04 20:15:26,159] {scheduler_job.py:182} INFO - Started process (PID=23017) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:15:26,160] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 20:15:26,161] {logging_mixin.py:104} INFO - [2024-08-04 20:15:26,160] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:15:26,172] {logging_mixin.py:104} INFO - [2024-08-04 20:15:26,171] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 20:15:26,173] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:15:26,233] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 20:15:57,002] {scheduler_job.py:182} INFO - Started process (PID=23047) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:15:57,002] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 20:15:57,003] {logging_mixin.py:104} INFO - [2024-08-04 20:15:57,003] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:15:57,010] {logging_mixin.py:104} INFO - [2024-08-04 20:15:57,009] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 20:15:57,011] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:15:57,070] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.070 seconds
[2024-08-04 20:16:31,161] {scheduler_job.py:182} INFO - Started process (PID=23075) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:16:31,162] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 20:16:31,162] {logging_mixin.py:104} INFO - [2024-08-04 20:16:31,162] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:16:31,172] {logging_mixin.py:104} INFO - [2024-08-04 20:16:31,170] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 20:16:31,174] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:16:31,235] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 20:28:33,353] {scheduler_job.py:182} INFO - Started process (PID=23104) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:28:33,354] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 20:28:33,355] {logging_mixin.py:104} INFO - [2024-08-04 20:28:33,355] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:28:33,363] {logging_mixin.py:104} INFO - [2024-08-04 20:28:33,362] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 20:28:33,364] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:28:33,437] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.086 seconds
[2024-08-04 20:29:03,549] {scheduler_job.py:182} INFO - Started process (PID=23133) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:29:03,550] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 20:29:03,550] {logging_mixin.py:104} INFO - [2024-08-04 20:29:03,550] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:29:03,558] {logging_mixin.py:104} INFO - [2024-08-04 20:29:03,557] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 20:29:03,558] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:29:03,616] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.068 seconds
[2024-08-04 20:43:19,121] {scheduler_job.py:182} INFO - Started process (PID=23162) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:43:19,121] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 20:43:19,122] {logging_mixin.py:104} INFO - [2024-08-04 20:43:19,122] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:43:19,132] {logging_mixin.py:104} INFO - [2024-08-04 20:43:19,130] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 20:43:19,132] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 20:43:19,202] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2024-08-04 21:00:12,215] {scheduler_job.py:182} INFO - Started process (PID=23191) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:00:12,216] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 21:00:12,217] {logging_mixin.py:104} INFO - [2024-08-04 21:00:12,217] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:00:12,229] {logging_mixin.py:104} INFO - [2024-08-04 21:00:12,228] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 21:00:12,231] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:00:12,292] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-04 21:00:43,476] {scheduler_job.py:182} INFO - Started process (PID=23228) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:00:43,477] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 21:00:43,477] {logging_mixin.py:104} INFO - [2024-08-04 21:00:43,477] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:00:43,488] {logging_mixin.py:104} INFO - [2024-08-04 21:00:43,487] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 21:00:43,489] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:00:43,551] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 21:50:27,984] {scheduler_job.py:182} INFO - Started process (PID=23249) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:50:27,986] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 21:50:27,987] {logging_mixin.py:104} INFO - [2024-08-04 21:50:27,987] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:50:28,000] {logging_mixin.py:104} INFO - [2024-08-04 21:50:27,996] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 21:50:28,004] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 21:50:28,065] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2024-08-04 22:17:28,573] {scheduler_job.py:182} INFO - Started process (PID=23278) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 22:17:28,574] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 22:17:28,578] {logging_mixin.py:104} INFO - [2024-08-04 22:17:28,578] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 22:17:28,587] {logging_mixin.py:104} INFO - [2024-08-04 22:17:28,586] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 22:17:28,589] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 22:17:28,654] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-04 22:53:00,284] {scheduler_job.py:182} INFO - Started process (PID=23307) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 22:53:00,285] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 22:53:00,285] {logging_mixin.py:104} INFO - [2024-08-04 22:53:00,285] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 22:53:00,294] {logging_mixin.py:104} INFO - [2024-08-04 22:53:00,293] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 22:53:00,295] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 22:53:00,358] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-04 23:18:24,772] {scheduler_job.py:182} INFO - Started process (PID=23336) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 23:18:24,772] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 23:18:24,773] {logging_mixin.py:104} INFO - [2024-08-04 23:18:24,773] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 23:18:24,781] {logging_mixin.py:104} INFO - [2024-08-04 23:18:24,780] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 23:18:24,782] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 23:18:24,871] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.101 seconds
[2024-08-04 23:36:44,753] {scheduler_job.py:182} INFO - Started process (PID=23365) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-04 23:36:44,753] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-04 23:36:44,754] {logging_mixin.py:104} INFO - [2024-08-04 23:36:44,754] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-04 23:36:44,766] {logging_mixin.py:104} INFO - [2024-08-04 23:36:44,766] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-04 23:36:44,770] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-04 23:36:44,830] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
