[2024-08-10 00:13:04,514] {scheduler_job.py:182} INFO - Started process (PID=60891) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 00:13:04,515] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 00:13:04,515] {logging_mixin.py:104} INFO - [2024-08-10 00:13:04,515] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 00:13:04,530] {logging_mixin.py:104} INFO - [2024-08-10 00:13:04,526] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 00:13:04,530] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 00:13:04,599] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.087 seconds
[2024-08-10 00:13:34,615] {scheduler_job.py:182} INFO - Started process (PID=60919) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 00:13:34,615] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 00:13:34,615] {logging_mixin.py:104} INFO - [2024-08-10 00:13:34,615] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 00:13:34,623] {logging_mixin.py:104} INFO - [2024-08-10 00:13:34,622] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 00:13:34,624] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 00:13:34,684] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-10 01:03:33,909] {scheduler_job.py:182} INFO - Started process (PID=60949) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:03:33,911] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 01:03:33,911] {logging_mixin.py:104} INFO - [2024-08-10 01:03:33,911] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:03:33,921] {logging_mixin.py:104} INFO - [2024-08-10 01:03:33,919] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 01:03:33,921] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:03:34,016] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.109 seconds
[2024-08-10 01:14:30,787] {scheduler_job.py:182} INFO - Started process (PID=60978) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:14:30,788] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 01:14:30,788] {logging_mixin.py:104} INFO - [2024-08-10 01:14:30,788] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:14:30,797] {logging_mixin.py:104} INFO - [2024-08-10 01:14:30,795] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 01:14:30,797] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:14:30,862] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-10 01:47:58,989] {scheduler_job.py:182} INFO - Started process (PID=61007) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:47:58,990] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 01:47:58,991] {logging_mixin.py:104} INFO - [2024-08-10 01:47:58,991] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:47:59,008] {logging_mixin.py:104} INFO - [2024-08-10 01:47:59,007] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 01:47:59,008] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 01:47:59,087] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.100 seconds
[2024-08-10 02:15:27,488] {scheduler_job.py:182} INFO - Started process (PID=61036) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:15:27,489] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 02:15:27,489] {logging_mixin.py:104} INFO - [2024-08-10 02:15:27,489] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:15:27,497] {logging_mixin.py:104} INFO - [2024-08-10 02:15:27,497] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 02:15:27,498] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:15:27,567] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2024-08-10 02:21:41,118] {scheduler_job.py:182} INFO - Started process (PID=61065) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:21:41,118] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 02:21:41,120] {logging_mixin.py:104} INFO - [2024-08-10 02:21:41,120] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:21:41,135] {logging_mixin.py:104} INFO - [2024-08-10 02:21:41,134] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 02:21:41,136] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:21:41,263] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.147 seconds
[2024-08-10 02:22:12,453] {scheduler_job.py:182} INFO - Started process (PID=61102) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:22:12,454] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 02:22:12,454] {logging_mixin.py:104} INFO - [2024-08-10 02:22:12,454] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:22:12,462] {logging_mixin.py:104} INFO - [2024-08-10 02:22:12,461] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 02:22:12,462] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 02:22:12,524] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-10 03:16:06,332] {scheduler_job.py:182} INFO - Started process (PID=61123) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 03:16:06,333] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 03:16:06,334] {logging_mixin.py:104} INFO - [2024-08-10 03:16:06,334] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 03:16:06,342] {logging_mixin.py:104} INFO - [2024-08-10 03:16:06,341] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 03:16:06,343] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 03:16:06,405] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-10 03:16:36,455] {scheduler_job.py:182} INFO - Started process (PID=61150) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 03:16:36,455] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 03:16:36,456] {logging_mixin.py:104} INFO - [2024-08-10 03:16:36,456] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 03:16:36,469] {logging_mixin.py:104} INFO - [2024-08-10 03:16:36,468] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 03:16:36,470] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 03:16:36,529] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-10 04:06:30,978] {scheduler_job.py:182} INFO - Started process (PID=61181) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 04:06:30,979] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 04:06:30,980] {logging_mixin.py:104} INFO - [2024-08-10 04:06:30,980] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 04:06:30,993] {logging_mixin.py:104} INFO - [2024-08-10 04:06:30,991] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 04:06:30,996] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 04:06:31,064] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.088 seconds
[2024-08-10 04:17:32,770] {scheduler_job.py:182} INFO - Started process (PID=61210) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 04:17:32,771] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 04:17:32,772] {logging_mixin.py:104} INFO - [2024-08-10 04:17:32,772] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 04:17:32,783] {logging_mixin.py:104} INFO - [2024-08-10 04:17:32,781] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 04:17:32,783] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 04:17:32,853] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2024-08-10 05:08:48,099] {scheduler_job.py:182} INFO - Started process (PID=61239) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:08:48,099] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 05:08:48,100] {logging_mixin.py:104} INFO - [2024-08-10 05:08:48,100] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:08:48,113] {logging_mixin.py:104} INFO - [2024-08-10 05:08:48,110] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 05:08:48,113] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:08:48,187] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.090 seconds
[2024-08-10 05:18:29,829] {scheduler_job.py:182} INFO - Started process (PID=61268) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:18:29,832] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 05:18:29,832] {logging_mixin.py:104} INFO - [2024-08-10 05:18:29,832] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:18:29,845] {logging_mixin.py:104} INFO - [2024-08-10 05:18:29,844] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 05:18:29,845] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:18:29,907] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-10 05:52:11,618] {scheduler_job.py:182} INFO - Started process (PID=61297) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:52:11,618] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 05:52:11,619] {logging_mixin.py:104} INFO - [2024-08-10 05:52:11,619] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:52:11,627] {logging_mixin.py:104} INFO - [2024-08-10 05:52:11,626] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 05:52:11,628] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 05:52:11,694] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-10 06:01:21,134] {scheduler_job.py:182} INFO - Started process (PID=61326) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:01:21,135] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 06:01:21,136] {logging_mixin.py:104} INFO - [2024-08-10 06:01:21,136] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:01:21,151] {logging_mixin.py:104} INFO - [2024-08-10 06:01:21,149] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 06:01:21,152] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:01:21,224] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.095 seconds
[2024-08-10 06:09:12,946] {scheduler_job.py:182} INFO - Started process (PID=61355) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:09:12,947] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 06:09:12,949] {logging_mixin.py:104} INFO - [2024-08-10 06:09:12,949] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:09:12,960] {logging_mixin.py:104} INFO - [2024-08-10 06:09:12,956] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 06:09:12,960] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:09:13,039] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.095 seconds
[2024-08-10 06:09:44,372] {scheduler_job.py:182} INFO - Started process (PID=61392) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:09:44,373] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 06:09:44,373] {logging_mixin.py:104} INFO - [2024-08-10 06:09:44,373] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:09:44,381] {logging_mixin.py:104} INFO - [2024-08-10 06:09:44,380] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 06:09:44,382] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:09:44,440] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.070 seconds
[2024-08-10 06:19:26,972] {scheduler_job.py:182} INFO - Started process (PID=61413) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:19:26,972] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 06:19:26,973] {logging_mixin.py:104} INFO - [2024-08-10 06:19:26,973] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:19:26,982] {logging_mixin.py:104} INFO - [2024-08-10 06:19:26,981] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 06:19:26,983] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:19:27,047] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-10 06:53:15,714] {scheduler_job.py:182} INFO - Started process (PID=61442) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:53:15,715] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 06:53:15,716] {logging_mixin.py:104} INFO - [2024-08-10 06:53:15,716] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:53:15,727] {logging_mixin.py:104} INFO - [2024-08-10 06:53:15,726] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 06:53:15,728] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 06:53:15,834] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.122 seconds
[2024-08-10 07:20:24,286] {scheduler_job.py:182} INFO - Started process (PID=61471) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:20:24,287] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 07:20:24,287] {logging_mixin.py:104} INFO - [2024-08-10 07:20:24,287] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:20:24,297] {logging_mixin.py:104} INFO - [2024-08-10 07:20:24,296] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 07:20:24,298] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:20:24,359] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-10 07:36:32,509] {scheduler_job.py:182} INFO - Started process (PID=61500) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:36:32,510] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 07:36:32,510] {logging_mixin.py:104} INFO - [2024-08-10 07:36:32,510] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:36:32,519] {logging_mixin.py:104} INFO - [2024-08-10 07:36:32,517] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 07:36:32,519] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:36:32,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2024-08-10 07:40:23,736] {scheduler_job.py:182} INFO - Started process (PID=61529) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:40:23,737] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 07:40:23,738] {logging_mixin.py:104} INFO - [2024-08-10 07:40:23,738] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:40:23,749] {logging_mixin.py:104} INFO - [2024-08-10 07:40:23,747] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 07:40:23,749] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 07:40:23,837] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.103 seconds
[2024-08-10 08:13:24,268] {scheduler_job.py:182} INFO - Started process (PID=61558) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:13:24,269] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:13:24,270] {logging_mixin.py:104} INFO - [2024-08-10 08:13:24,270] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:13:24,282] {logging_mixin.py:104} INFO - [2024-08-10 08:13:24,278] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:13:24,283] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:13:24,347] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2024-08-10 08:16:04,215] {scheduler_job.py:182} INFO - Started process (PID=61587) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:16:04,216] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:16:04,217] {logging_mixin.py:104} INFO - [2024-08-10 08:16:04,217] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:16:04,263] {logging_mixin.py:104} INFO - [2024-08-10 08:16:04,252] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:16:04,266] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:16:04,343] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.136 seconds
[2024-08-10 08:16:34,433] {scheduler_job.py:182} INFO - Started process (PID=61616) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:16:34,434] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:16:34,434] {logging_mixin.py:104} INFO - [2024-08-10 08:16:34,434] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:16:34,442] {logging_mixin.py:104} INFO - [2024-08-10 08:16:34,441] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:16:34,442] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:16:34,500] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.068 seconds
[2024-08-10 08:17:04,964] {scheduler_job.py:182} INFO - Started process (PID=61642) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:17:04,965] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:17:04,965] {logging_mixin.py:104} INFO - [2024-08-10 08:17:04,965] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:17:04,973] {logging_mixin.py:104} INFO - [2024-08-10 08:17:04,972] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:17:04,974] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:17:05,034] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-10 08:17:35,851] {scheduler_job.py:182} INFO - Started process (PID=61671) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:17:35,851] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:17:35,852] {logging_mixin.py:104} INFO - [2024-08-10 08:17:35,852] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:17:35,860] {logging_mixin.py:104} INFO - [2024-08-10 08:17:35,859] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:17:35,860] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:17:35,921] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-10 08:18:06,692] {scheduler_job.py:182} INFO - Started process (PID=61702) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:18:06,692] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:18:06,693] {logging_mixin.py:104} INFO - [2024-08-10 08:18:06,693] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:18:06,700] {logging_mixin.py:104} INFO - [2024-08-10 08:18:06,699] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:18:06,701] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:18:06,761] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-10 08:18:37,472] {scheduler_job.py:182} INFO - Started process (PID=61731) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:18:37,473] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:18:37,474] {logging_mixin.py:104} INFO - [2024-08-10 08:18:37,474] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:18:37,482] {logging_mixin.py:104} INFO - [2024-08-10 08:18:37,481] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:18:37,482] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:18:37,543] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-10 08:19:08,179] {scheduler_job.py:182} INFO - Started process (PID=61758) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:19:08,180] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:19:08,180] {logging_mixin.py:104} INFO - [2024-08-10 08:19:08,180] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:19:08,189] {logging_mixin.py:104} INFO - [2024-08-10 08:19:08,188] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:19:08,189] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:19:08,250] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-10 08:19:39,010] {scheduler_job.py:182} INFO - Started process (PID=61789) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:19:39,011] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:19:39,011] {logging_mixin.py:104} INFO - [2024-08-10 08:19:39,011] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:19:39,019] {logging_mixin.py:104} INFO - [2024-08-10 08:19:39,019] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:19:39,020] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:19:39,082] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-10 08:20:09,720] {scheduler_job.py:182} INFO - Started process (PID=61817) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:20:09,720] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:20:09,723] {logging_mixin.py:104} INFO - [2024-08-10 08:20:09,723] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:20:09,731] {logging_mixin.py:104} INFO - [2024-08-10 08:20:09,730] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:20:09,732] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:20:09,791] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-10 08:20:40,438] {scheduler_job.py:182} INFO - Started process (PID=61845) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:20:40,439] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:20:40,439] {logging_mixin.py:104} INFO - [2024-08-10 08:20:40,439] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:20:40,447] {logging_mixin.py:104} INFO - [2024-08-10 08:20:40,446] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:20:40,447] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:20:40,510] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-10 08:21:11,223] {scheduler_job.py:182} INFO - Started process (PID=61875) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:21:11,223] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:21:11,224] {logging_mixin.py:104} INFO - [2024-08-10 08:21:11,224] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:21:11,233] {logging_mixin.py:104} INFO - [2024-08-10 08:21:11,232] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:21:11,237] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:21:11,301] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-10 08:21:42,047] {scheduler_job.py:182} INFO - Started process (PID=61904) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:21:42,048] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:21:42,049] {logging_mixin.py:104} INFO - [2024-08-10 08:21:42,049] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:21:42,056] {logging_mixin.py:104} INFO - [2024-08-10 08:21:42,056] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:21:42,057] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:21:42,119] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-10 08:22:12,834] {scheduler_job.py:182} INFO - Started process (PID=61933) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:22:12,835] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:22:12,835] {logging_mixin.py:104} INFO - [2024-08-10 08:22:12,835] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:22:12,844] {logging_mixin.py:104} INFO - [2024-08-10 08:22:12,843] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:22:12,845] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:22:12,907] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-10 08:22:43,584] {scheduler_job.py:182} INFO - Started process (PID=61962) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:22:43,585] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 08:22:43,588] {logging_mixin.py:104} INFO - [2024-08-10 08:22:43,588] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:22:43,597] {logging_mixin.py:104} INFO - [2024-08-10 08:22:43,596] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 08:22:43,597] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 08:22:43,659] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-10 19:59:43,680] {scheduler_job.py:182} INFO - Started process (PID=38) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 19:59:43,681] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 19:59:43,682] {logging_mixin.py:104} INFO - [2024-08-10 19:59:43,682] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 19:59:43,696] {logging_mixin.py:104} INFO - [2024-08-10 19:59:43,694] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 19:59:43,700] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 19:59:43,775] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.097 seconds
[2024-08-10 20:00:14,641] {scheduler_job.py:182} INFO - Started process (PID=67) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 20:00:14,642] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 20:00:14,642] {logging_mixin.py:104} INFO - [2024-08-10 20:00:14,642] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 20:00:14,650] {logging_mixin.py:104} INFO - [2024-08-10 20:00:14,649] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 20:00:14,650] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 20:00:14,709] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.069 seconds
[2024-08-10 21:00:36,726] {scheduler_job.py:182} INFO - Started process (PID=96) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:00:36,728] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 21:00:36,730] {logging_mixin.py:104} INFO - [2024-08-10 21:00:36,730] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:00:36,739] {logging_mixin.py:104} INFO - [2024-08-10 21:00:36,738] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 21:00:36,742] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:00:36,803] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-10 21:01:07,650] {scheduler_job.py:182} INFO - Started process (PID=125) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:01:07,650] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 21:01:07,651] {logging_mixin.py:104} INFO - [2024-08-10 21:01:07,651] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:01:07,661] {logging_mixin.py:104} INFO - [2024-08-10 21:01:07,660] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 21:01:07,662] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:01:07,720] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-10 21:16:45,064] {scheduler_job.py:182} INFO - Started process (PID=154) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:16:45,065] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 21:16:45,065] {logging_mixin.py:104} INFO - [2024-08-10 21:16:45,065] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:16:45,076] {logging_mixin.py:104} INFO - [2024-08-10 21:16:45,075] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 21:16:45,076] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:16:45,139] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-10 21:21:47,573] {scheduler_job.py:182} INFO - Started process (PID=183) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:21:47,574] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 21:21:47,574] {logging_mixin.py:104} INFO - [2024-08-10 21:21:47,574] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:21:47,581] {logging_mixin.py:104} INFO - [2024-08-10 21:21:47,581] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 21:21:47,582] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:21:47,640] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.069 seconds
[2024-08-10 21:22:18,653] {scheduler_job.py:182} INFO - Started process (PID=212) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:22:18,654] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 21:22:18,654] {logging_mixin.py:104} INFO - [2024-08-10 21:22:18,654] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:22:18,661] {logging_mixin.py:104} INFO - [2024-08-10 21:22:18,660] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 21:22:18,662] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:22:18,721] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.070 seconds
[2024-08-10 21:45:45,206] {scheduler_job.py:182} INFO - Started process (PID=241) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:45:45,209] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 21:45:45,210] {logging_mixin.py:104} INFO - [2024-08-10 21:45:45,209] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:45:45,217] {logging_mixin.py:104} INFO - [2024-08-10 21:45:45,216] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 21:45:45,218] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:45:45,277] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-10 21:46:16,414] {scheduler_job.py:182} INFO - Started process (PID=270) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:46:16,415] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 21:46:16,415] {logging_mixin.py:104} INFO - [2024-08-10 21:46:16,415] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:46:16,425] {logging_mixin.py:104} INFO - [2024-08-10 21:46:16,422] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 21:46:16,426] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 21:46:16,484] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-10 22:01:46,704] {scheduler_job.py:182} INFO - Started process (PID=299) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:01:46,706] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:01:46,707] {logging_mixin.py:104} INFO - [2024-08-10 22:01:46,707] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:01:46,717] {logging_mixin.py:104} INFO - [2024-08-10 22:01:46,717] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:01:46,720] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:01:46,787] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2024-08-10 22:08:19,455] {scheduler_job.py:182} INFO - Started process (PID=328) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:08:19,456] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:08:19,456] {logging_mixin.py:104} INFO - [2024-08-10 22:08:19,456] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:08:19,464] {logging_mixin.py:104} INFO - [2024-08-10 22:08:19,463] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:08:19,465] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:08:19,526] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-10 22:08:49,771] {scheduler_job.py:182} INFO - Started process (PID=358) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:08:49,773] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:08:49,774] {logging_mixin.py:104} INFO - [2024-08-10 22:08:49,774] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:08:49,782] {logging_mixin.py:104} INFO - [2024-08-10 22:08:49,782] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:08:49,783] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:08:49,843] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-10 22:13:48,170] {scheduler_job.py:182} INFO - Started process (PID=386) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:13:48,171] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:13:48,171] {logging_mixin.py:104} INFO - [2024-08-10 22:13:48,171] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:13:48,179] {logging_mixin.py:104} INFO - [2024-08-10 22:13:48,178] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:13:48,182] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:13:48,254] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.086 seconds
[2024-08-10 22:17:45,474] {scheduler_job.py:182} INFO - Started process (PID=415) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:17:45,478] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:17:45,478] {logging_mixin.py:104} INFO - [2024-08-10 22:17:45,478] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:17:45,489] {logging_mixin.py:104} INFO - [2024-08-10 22:17:45,485] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:17:45,489] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:17:45,605] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.133 seconds
[2024-08-10 22:18:16,485] {scheduler_job.py:182} INFO - Started process (PID=444) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:18:16,486] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:18:16,486] {logging_mixin.py:104} INFO - [2024-08-10 22:18:16,486] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:18:16,494] {logging_mixin.py:104} INFO - [2024-08-10 22:18:16,493] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:18:16,496] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:18:16,555] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-10 22:18:47,181] {scheduler_job.py:182} INFO - Started process (PID=473) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:18:47,182] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:18:47,182] {logging_mixin.py:104} INFO - [2024-08-10 22:18:47,182] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:18:47,191] {logging_mixin.py:104} INFO - [2024-08-10 22:18:47,189] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:18:47,191] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:18:47,252] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-10 22:19:18,321] {scheduler_job.py:182} INFO - Started process (PID=504) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:19:18,321] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:19:18,322] {logging_mixin.py:104} INFO - [2024-08-10 22:19:18,322] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:19:18,329] {logging_mixin.py:104} INFO - [2024-08-10 22:19:18,328] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:19:18,330] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:19:18,388] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.069 seconds
[2024-08-10 22:27:20,265] {scheduler_job.py:182} INFO - Started process (PID=531) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:27:20,265] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 22:27:20,266] {logging_mixin.py:104} INFO - [2024-08-10 22:27:20,266] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:27:20,274] {logging_mixin.py:104} INFO - [2024-08-10 22:27:20,273] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 22:27:20,274] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 22:27:20,337] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-10 23:00:13,133] {scheduler_job.py:182} INFO - Started process (PID=560) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:00:13,137] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 23:00:13,141] {logging_mixin.py:104} INFO - [2024-08-10 23:00:13,141] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:00:13,157] {logging_mixin.py:104} INFO - [2024-08-10 23:00:13,156] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 23:00:13,158] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:00:13,227] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.096 seconds
[2024-08-10 23:02:53,806] {scheduler_job.py:182} INFO - Started process (PID=589) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:02:53,807] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 23:02:53,809] {logging_mixin.py:104} INFO - [2024-08-10 23:02:53,809] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:02:53,819] {logging_mixin.py:104} INFO - [2024-08-10 23:02:53,818] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 23:02:53,819] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:02:53,883] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-10 23:14:08,207] {scheduler_job.py:182} INFO - Started process (PID=618) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:14:08,209] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 23:14:08,210] {logging_mixin.py:104} INFO - [2024-08-10 23:14:08,209] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:14:08,217] {logging_mixin.py:104} INFO - [2024-08-10 23:14:08,217] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 23:14:08,218] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:14:08,276] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.070 seconds
[2024-08-10 23:14:39,175] {scheduler_job.py:182} INFO - Started process (PID=647) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:14:39,176] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-10 23:14:39,176] {logging_mixin.py:104} INFO - [2024-08-10 23:14:39,176] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:14:39,186] {logging_mixin.py:104} INFO - [2024-08-10 23:14:39,184] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-10 23:14:39,187] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-10 23:14:39,245] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
