[2024-08-08 00:27:41,114] {scheduler_job.py:182} INFO - Started process (PID=52945) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 00:27:41,115] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 00:27:41,116] {logging_mixin.py:104} INFO - [2024-08-08 00:27:41,116] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 00:27:41,132] {logging_mixin.py:104} INFO - [2024-08-08 00:27:41,130] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 00:27:41,133] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 00:27:41,195] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2024-08-08 00:37:44,693] {scheduler_job.py:182} INFO - Started process (PID=52974) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 00:37:44,693] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 00:37:44,694] {logging_mixin.py:104} INFO - [2024-08-08 00:37:44,694] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 00:37:44,703] {logging_mixin.py:104} INFO - [2024-08-08 00:37:44,701] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 00:37:44,704] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 00:37:44,766] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 01:10:26,310] {scheduler_job.py:182} INFO - Started process (PID=53003) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:10:26,311] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 01:10:26,315] {logging_mixin.py:104} INFO - [2024-08-08 01:10:26,315] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:10:26,327] {logging_mixin.py:104} INFO - [2024-08-08 01:10:26,326] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 01:10:26,327] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:10:26,390] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-08 01:38:41,607] {scheduler_job.py:182} INFO - Started process (PID=53032) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:38:41,607] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 01:38:41,608] {logging_mixin.py:104} INFO - [2024-08-08 01:38:41,608] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:38:41,616] {logging_mixin.py:104} INFO - [2024-08-08 01:38:41,615] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 01:38:41,617] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:38:41,694] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.089 seconds
[2024-08-08 01:56:04,004] {scheduler_job.py:182} INFO - Started process (PID=53061) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:56:04,005] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 01:56:04,005] {logging_mixin.py:104} INFO - [2024-08-08 01:56:04,005] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:56:04,014] {logging_mixin.py:104} INFO - [2024-08-08 01:56:04,013] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 01:56:04,015] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 01:56:04,076] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 02:25:57,920] {scheduler_job.py:182} INFO - Started process (PID=53090) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:25:57,920] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 02:25:57,921] {logging_mixin.py:104} INFO - [2024-08-08 02:25:57,921] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:25:57,930] {logging_mixin.py:104} INFO - [2024-08-08 02:25:57,929] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 02:25:57,931] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:25:57,994] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-08 02:39:26,355] {scheduler_job.py:182} INFO - Started process (PID=53119) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:39:26,356] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 02:39:26,357] {logging_mixin.py:104} INFO - [2024-08-08 02:39:26,357] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:39:26,365] {logging_mixin.py:104} INFO - [2024-08-08 02:39:26,364] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 02:39:26,366] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:39:26,449] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.095 seconds
[2024-08-08 02:39:56,516] {scheduler_job.py:182} INFO - Started process (PID=53147) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:39:56,517] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 02:39:56,518] {logging_mixin.py:104} INFO - [2024-08-08 02:39:56,518] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:39:56,525] {logging_mixin.py:104} INFO - [2024-08-08 02:39:56,524] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 02:39:56,528] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 02:39:56,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 03:40:22,420] {scheduler_job.py:182} INFO - Started process (PID=53177) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 03:40:22,421] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 03:40:22,422] {logging_mixin.py:104} INFO - [2024-08-08 03:40:22,422] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 03:40:22,449] {logging_mixin.py:104} INFO - [2024-08-08 03:40:22,447] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 03:40:22,454] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 03:40:22,531] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.118 seconds
[2024-08-08 03:40:53,737] {scheduler_job.py:182} INFO - Started process (PID=53214) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 03:40:53,738] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 03:40:53,738] {logging_mixin.py:104} INFO - [2024-08-08 03:40:53,738] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 03:40:53,746] {logging_mixin.py:104} INFO - [2024-08-08 03:40:53,745] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 03:40:53,747] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 03:40:53,807] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 04:32:19,949] {scheduler_job.py:182} INFO - Started process (PID=53235) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:32:19,950] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 04:32:19,950] {logging_mixin.py:104} INFO - [2024-08-08 04:32:19,950] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:32:19,960] {logging_mixin.py:104} INFO - [2024-08-08 04:32:19,959] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 04:32:19,961] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:32:20,032] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.087 seconds
[2024-08-08 04:41:49,717] {scheduler_job.py:182} INFO - Started process (PID=53264) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:41:49,718] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 04:41:49,718] {logging_mixin.py:104} INFO - [2024-08-08 04:41:49,718] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:41:49,731] {logging_mixin.py:104} INFO - [2024-08-08 04:41:49,730] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 04:41:49,732] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:41:49,795] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-08 04:43:05,517] {scheduler_job.py:182} INFO - Started process (PID=53293) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:43:05,518] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 04:43:05,519] {logging_mixin.py:104} INFO - [2024-08-08 04:43:05,519] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:43:05,528] {logging_mixin.py:104} INFO - [2024-08-08 04:43:05,527] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 04:43:05,528] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:43:05,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 04:43:36,731] {scheduler_job.py:182} INFO - Started process (PID=53330) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:43:36,732] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 04:43:36,732] {logging_mixin.py:104} INFO - [2024-08-08 04:43:36,732] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:43:36,741] {logging_mixin.py:104} INFO - [2024-08-08 04:43:36,740] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 04:43:36,742] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 04:43:36,803] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 05:00:56,526] {scheduler_job.py:182} INFO - Started process (PID=53351) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:00:56,527] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 05:00:56,527] {logging_mixin.py:104} INFO - [2024-08-08 05:00:56,527] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:00:56,537] {logging_mixin.py:104} INFO - [2024-08-08 05:00:56,535] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 05:00:56,539] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:00:56,600] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 05:23:44,761] {scheduler_job.py:182} INFO - Started process (PID=53380) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:23:44,762] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 05:23:44,762] {logging_mixin.py:104} INFO - [2024-08-08 05:23:44,762] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:23:44,771] {logging_mixin.py:104} INFO - [2024-08-08 05:23:44,770] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 05:23:44,771] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:23:44,833] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 05:24:16,146] {scheduler_job.py:182} INFO - Started process (PID=53417) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:24:16,146] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 05:24:16,147] {logging_mixin.py:104} INFO - [2024-08-08 05:24:16,147] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:24:16,156] {logging_mixin.py:104} INFO - [2024-08-08 05:24:16,155] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 05:24:16,156] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:24:16,216] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 05:31:50,051] {scheduler_job.py:182} INFO - Started process (PID=53438) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:31:50,052] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 05:31:50,053] {logging_mixin.py:104} INFO - [2024-08-08 05:31:50,053] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:31:50,062] {logging_mixin.py:104} INFO - [2024-08-08 05:31:50,061] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 05:31:50,063] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:31:50,157] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.108 seconds
[2024-08-08 05:32:20,987] {scheduler_job.py:182} INFO - Started process (PID=53466) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:32:20,988] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 05:32:20,988] {logging_mixin.py:104} INFO - [2024-08-08 05:32:20,988] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:32:20,996] {logging_mixin.py:104} INFO - [2024-08-08 05:32:20,995] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 05:32:20,996] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:32:21,057] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 05:42:48,338] {scheduler_job.py:182} INFO - Started process (PID=53496) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:42:48,339] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 05:42:48,340] {logging_mixin.py:104} INFO - [2024-08-08 05:42:48,339] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:42:48,351] {logging_mixin.py:104} INFO - [2024-08-08 05:42:48,349] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 05:42:48,352] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 05:42:48,441] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.105 seconds
[2024-08-08 06:31:19,760] {scheduler_job.py:182} INFO - Started process (PID=53525) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 06:31:19,761] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 06:31:19,762] {logging_mixin.py:104} INFO - [2024-08-08 06:31:19,761] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 06:31:19,772] {logging_mixin.py:104} INFO - [2024-08-08 06:31:19,771] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 06:31:19,773] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 06:31:19,843] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2024-08-08 06:43:44,489] {scheduler_job.py:182} INFO - Started process (PID=53554) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 06:43:44,490] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 06:43:44,491] {logging_mixin.py:104} INFO - [2024-08-08 06:43:44,491] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 06:43:44,500] {logging_mixin.py:104} INFO - [2024-08-08 06:43:44,499] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 06:43:44,501] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 06:43:44,570] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-08 07:16:16,204] {scheduler_job.py:182} INFO - Started process (PID=53583) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 07:16:16,205] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 07:16:16,205] {logging_mixin.py:104} INFO - [2024-08-08 07:16:16,205] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 07:16:16,216] {logging_mixin.py:104} INFO - [2024-08-08 07:16:16,214] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 07:16:16,216] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 07:16:16,295] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.093 seconds
[2024-08-08 07:44:42,331] {scheduler_job.py:182} INFO - Started process (PID=53612) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 07:44:42,332] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 07:44:42,333] {logging_mixin.py:104} INFO - [2024-08-08 07:44:42,333] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 07:44:42,343] {logging_mixin.py:104} INFO - [2024-08-08 07:44:42,342] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 07:44:42,344] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 07:44:42,415] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.086 seconds
[2024-08-08 08:02:17,724] {scheduler_job.py:182} INFO - Started process (PID=53641) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:02:17,725] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 08:02:17,725] {logging_mixin.py:104} INFO - [2024-08-08 08:02:17,725] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:02:17,734] {logging_mixin.py:104} INFO - [2024-08-08 08:02:17,733] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 08:02:17,735] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:02:17,797] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 08:27:59,169] {scheduler_job.py:182} INFO - Started process (PID=53670) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:27:59,170] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 08:27:59,171] {logging_mixin.py:104} INFO - [2024-08-08 08:27:59,171] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:27:59,188] {logging_mixin.py:104} INFO - [2024-08-08 08:27:59,187] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 08:27:59,189] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:27:59,264] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.096 seconds
[2024-08-08 08:32:19,774] {scheduler_job.py:182} INFO - Started process (PID=53699) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:32:19,776] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 08:32:19,777] {logging_mixin.py:104} INFO - [2024-08-08 08:32:19,776] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:32:19,787] {logging_mixin.py:104} INFO - [2024-08-08 08:32:19,786] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 08:32:19,787] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:32:19,854] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2024-08-08 08:32:51,367] {scheduler_job.py:182} INFO - Started process (PID=53736) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:32:51,367] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 08:32:51,368] {logging_mixin.py:104} INFO - [2024-08-08 08:32:51,368] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:32:51,379] {logging_mixin.py:104} INFO - [2024-08-08 08:32:51,376] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 08:32:51,379] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:32:51,440] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 08:45:40,567] {scheduler_job.py:182} INFO - Started process (PID=53757) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:45:40,568] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 08:45:40,568] {logging_mixin.py:104} INFO - [2024-08-08 08:45:40,568] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:45:40,579] {logging_mixin.py:104} INFO - [2024-08-08 08:45:40,578] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 08:45:40,580] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 08:45:40,648] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2024-08-08 09:03:29,501] {scheduler_job.py:182} INFO - Started process (PID=53786) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:03:29,502] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:03:29,502] {logging_mixin.py:104} INFO - [2024-08-08 09:03:29,502] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:03:29,511] {logging_mixin.py:104} INFO - [2024-08-08 09:03:29,510] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:03:29,512] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:03:29,591] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.091 seconds
[2024-08-08 09:17:13,591] {scheduler_job.py:182} INFO - Started process (PID=53815) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:17:13,592] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:17:13,593] {logging_mixin.py:104} INFO - [2024-08-08 09:17:13,593] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:17:13,602] {logging_mixin.py:104} INFO - [2024-08-08 09:17:13,601] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:17:13,603] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:17:13,672] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-08 09:17:44,514] {scheduler_job.py:182} INFO - Started process (PID=53847) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:17:44,515] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:17:44,515] {logging_mixin.py:104} INFO - [2024-08-08 09:17:44,515] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:17:44,523] {logging_mixin.py:104} INFO - [2024-08-08 09:17:44,522] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:17:44,523] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:17:44,580] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.068 seconds
[2024-08-08 09:18:15,614] {scheduler_job.py:182} INFO - Started process (PID=53881) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:18:15,615] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:18:15,616] {logging_mixin.py:104} INFO - [2024-08-08 09:18:15,616] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:18:15,624] {logging_mixin.py:104} INFO - [2024-08-08 09:18:15,623] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:18:15,624] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:18:15,683] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 09:18:51,463] {scheduler_job.py:182} INFO - Started process (PID=53902) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:18:51,463] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:18:51,467] {logging_mixin.py:104} INFO - [2024-08-08 09:18:51,467] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:18:51,475] {logging_mixin.py:104} INFO - [2024-08-08 09:18:51,474] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:18:51,475] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:18:51,536] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 09:20:10,487] {scheduler_job.py:182} INFO - Started process (PID=53931) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:20:10,487] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:20:10,488] {logging_mixin.py:104} INFO - [2024-08-08 09:20:10,488] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:20:10,499] {logging_mixin.py:104} INFO - [2024-08-08 09:20:10,498] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:20:10,499] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:20:10,561] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-08 09:20:41,845] {scheduler_job.py:182} INFO - Started process (PID=53968) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:20:41,846] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:20:41,846] {logging_mixin.py:104} INFO - [2024-08-08 09:20:41,846] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:20:41,856] {logging_mixin.py:104} INFO - [2024-08-08 09:20:41,854] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:20:41,856] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:20:41,916] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 09:24:17,489] {scheduler_job.py:182} INFO - Started process (PID=53989) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:24:17,490] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:24:17,491] {logging_mixin.py:104} INFO - [2024-08-08 09:24:17,490] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:24:17,501] {logging_mixin.py:104} INFO - [2024-08-08 09:24:17,498] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:24:17,502] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:24:17,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.101 seconds
[2024-08-08 09:30:04,193] {scheduler_job.py:182} INFO - Started process (PID=54018) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:30:04,194] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:30:04,195] {logging_mixin.py:104} INFO - [2024-08-08 09:30:04,195] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:30:04,207] {logging_mixin.py:104} INFO - [2024-08-08 09:30:04,206] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:30:04,208] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:30:04,272] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-08 09:30:35,505] {scheduler_job.py:182} INFO - Started process (PID=54055) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:30:35,506] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:30:35,507] {logging_mixin.py:104} INFO - [2024-08-08 09:30:35,507] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:30:35,516] {logging_mixin.py:104} INFO - [2024-08-08 09:30:35,515] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:30:35,516] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:30:35,578] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 09:43:02,407] {scheduler_job.py:182} INFO - Started process (PID=54076) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:43:02,408] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:43:02,408] {logging_mixin.py:104} INFO - [2024-08-08 09:43:02,408] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:43:02,416] {logging_mixin.py:104} INFO - [2024-08-08 09:43:02,415] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:43:02,417] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:43:02,477] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 09:43:33,363] {scheduler_job.py:182} INFO - Started process (PID=54104) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:43:33,364] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:43:33,364] {logging_mixin.py:104} INFO - [2024-08-08 09:43:33,364] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:43:33,373] {logging_mixin.py:104} INFO - [2024-08-08 09:43:33,372] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:43:33,373] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:43:33,820] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.459 seconds
[2024-08-08 09:44:08,178] {scheduler_job.py:182} INFO - Started process (PID=54134) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:44:08,179] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:44:08,181] {logging_mixin.py:104} INFO - [2024-08-08 09:44:08,181] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:44:08,190] {logging_mixin.py:104} INFO - [2024-08-08 09:44:08,189] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:44:08,190] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:44:08,251] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 09:46:31,806] {scheduler_job.py:182} INFO - Started process (PID=54163) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:46:31,807] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:46:31,809] {logging_mixin.py:104} INFO - [2024-08-08 09:46:31,809] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:46:31,818] {logging_mixin.py:104} INFO - [2024-08-08 09:46:31,816] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:46:31,819] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:46:31,879] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 09:47:03,160] {scheduler_job.py:182} INFO - Started process (PID=54200) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:47:03,160] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 09:47:03,161] {logging_mixin.py:104} INFO - [2024-08-08 09:47:03,161] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:47:03,170] {logging_mixin.py:104} INFO - [2024-08-08 09:47:03,168] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 09:47:03,170] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 09:47:03,230] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 10:47:29,577] {scheduler_job.py:182} INFO - Started process (PID=54221) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 10:47:29,578] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 10:47:29,578] {logging_mixin.py:104} INFO - [2024-08-08 10:47:29,578] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 10:47:29,587] {logging_mixin.py:104} INFO - [2024-08-08 10:47:29,586] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 10:47:29,588] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 10:47:29,649] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 10:47:59,709] {scheduler_job.py:182} INFO - Started process (PID=54249) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 10:47:59,709] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 10:47:59,710] {logging_mixin.py:104} INFO - [2024-08-08 10:47:59,710] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 10:47:59,718] {logging_mixin.py:104} INFO - [2024-08-08 10:47:59,717] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 10:47:59,718] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 10:47:59,778] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 11:21:22,136] {scheduler_job.py:182} INFO - Started process (PID=54279) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:21:22,137] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 11:21:22,138] {logging_mixin.py:104} INFO - [2024-08-08 11:21:22,138] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:21:22,152] {logging_mixin.py:104} INFO - [2024-08-08 11:21:22,148] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 11:21:22,152] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:21:22,233] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.098 seconds
[2024-08-08 11:21:53,554] {scheduler_job.py:182} INFO - Started process (PID=54316) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:21:53,555] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 11:21:53,555] {logging_mixin.py:104} INFO - [2024-08-08 11:21:53,555] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:21:53,563] {logging_mixin.py:104} INFO - [2024-08-08 11:21:53,562] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 11:21:53,563] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:21:53,622] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.070 seconds
[2024-08-08 11:38:04,554] {scheduler_job.py:182} INFO - Started process (PID=54337) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:38:04,555] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 11:38:04,555] {logging_mixin.py:104} INFO - [2024-08-08 11:38:04,555] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:38:04,564] {logging_mixin.py:104} INFO - [2024-08-08 11:38:04,563] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 11:38:04,565] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:38:04,630] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-08 11:48:26,613] {scheduler_job.py:182} INFO - Started process (PID=54366) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:48:26,614] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 11:48:26,614] {logging_mixin.py:104} INFO - [2024-08-08 11:48:26,614] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:48:26,625] {logging_mixin.py:104} INFO - [2024-08-08 11:48:26,623] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 11:48:26,626] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:48:26,689] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-08 11:48:57,964] {scheduler_job.py:182} INFO - Started process (PID=54403) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:48:57,965] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 11:48:57,965] {logging_mixin.py:104} INFO - [2024-08-08 11:48:57,965] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:48:57,973] {logging_mixin.py:104} INFO - [2024-08-08 11:48:57,972] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 11:48:57,974] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 11:48:58,035] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 12:25:53,166] {scheduler_job.py:182} INFO - Started process (PID=54424) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:25:53,169] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 12:25:53,170] {logging_mixin.py:104} INFO - [2024-08-08 12:25:53,170] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:25:53,179] {logging_mixin.py:104} INFO - [2024-08-08 12:25:53,178] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 12:25:53,179] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:25:53,256] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.092 seconds
[2024-08-08 12:26:24,479] {scheduler_job.py:182} INFO - Started process (PID=54461) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:26:24,483] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 12:26:24,483] {logging_mixin.py:104} INFO - [2024-08-08 12:26:24,483] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:26:24,491] {logging_mixin.py:104} INFO - [2024-08-08 12:26:24,490] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 12:26:24,491] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:26:24,552] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 12:49:37,237] {scheduler_job.py:182} INFO - Started process (PID=54482) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:49:37,239] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 12:49:37,239] {logging_mixin.py:104} INFO - [2024-08-08 12:49:37,239] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:49:37,248] {logging_mixin.py:104} INFO - [2024-08-08 12:49:37,247] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 12:49:37,249] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:49:37,317] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2024-08-08 12:50:08,595] {scheduler_job.py:182} INFO - Started process (PID=54519) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:50:08,596] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 12:50:08,596] {logging_mixin.py:104} INFO - [2024-08-08 12:50:08,596] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:50:08,604] {logging_mixin.py:104} INFO - [2024-08-08 12:50:08,603] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 12:50:08,605] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:50:08,666] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 12:56:19,412] {scheduler_job.py:182} INFO - Started process (PID=54540) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:56:19,413] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 12:56:19,413] {logging_mixin.py:104} INFO - [2024-08-08 12:56:19,413] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:56:19,423] {logging_mixin.py:104} INFO - [2024-08-08 12:56:19,422] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 12:56:19,423] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 12:56:19,501] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.091 seconds
[2024-08-08 13:31:46,954] {scheduler_job.py:182} INFO - Started process (PID=54569) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:31:46,956] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 13:31:46,956] {logging_mixin.py:104} INFO - [2024-08-08 13:31:46,956] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:31:46,965] {logging_mixin.py:104} INFO - [2024-08-08 13:31:46,964] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 13:31:46,966] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:31:47,026] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 13:44:09,666] {scheduler_job.py:182} INFO - Started process (PID=54598) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:44:09,666] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 13:44:09,667] {logging_mixin.py:104} INFO - [2024-08-08 13:44:09,667] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:44:09,676] {logging_mixin.py:104} INFO - [2024-08-08 13:44:09,675] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 13:44:09,678] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:44:09,739] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 13:50:36,663] {scheduler_job.py:182} INFO - Started process (PID=54627) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:50:36,663] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 13:50:36,664] {logging_mixin.py:104} INFO - [2024-08-08 13:50:36,664] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:50:36,676] {logging_mixin.py:104} INFO - [2024-08-08 13:50:36,672] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 13:50:36,676] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:50:36,738] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-08 13:51:08,047] {scheduler_job.py:182} INFO - Started process (PID=54664) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:51:08,048] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 13:51:08,048] {logging_mixin.py:104} INFO - [2024-08-08 13:51:08,048] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:51:08,057] {logging_mixin.py:104} INFO - [2024-08-08 13:51:08,055] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 13:51:08,057] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 13:51:08,118] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 14:51:34,384] {scheduler_job.py:182} INFO - Started process (PID=54685) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 14:51:34,388] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 14:51:34,391] {logging_mixin.py:104} INFO - [2024-08-08 14:51:34,391] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 14:51:34,404] {logging_mixin.py:104} INFO - [2024-08-08 14:51:34,403] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 14:51:34,405] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 14:51:34,474] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.092 seconds
[2024-08-08 14:52:05,883] {scheduler_job.py:182} INFO - Started process (PID=54722) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 14:52:05,884] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 14:52:05,884] {logging_mixin.py:104} INFO - [2024-08-08 14:52:05,884] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 14:52:05,893] {logging_mixin.py:104} INFO - [2024-08-08 14:52:05,892] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 14:52:05,894] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 14:52:05,954] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 15:47:01,502] {scheduler_job.py:182} INFO - Started process (PID=54743) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:47:01,503] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 15:47:01,504] {logging_mixin.py:104} INFO - [2024-08-08 15:47:01,504] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:47:01,519] {logging_mixin.py:104} INFO - [2024-08-08 15:47:01,513] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 15:47:01,519] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:47:01,589] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.089 seconds
[2024-08-08 15:47:32,742] {scheduler_job.py:182} INFO - Started process (PID=54780) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:47:32,742] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 15:47:32,743] {logging_mixin.py:104} INFO - [2024-08-08 15:47:32,743] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:47:32,751] {logging_mixin.py:104} INFO - [2024-08-08 15:47:32,750] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 15:47:32,752] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:47:32,811] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 15:52:44,206] {scheduler_job.py:182} INFO - Started process (PID=54801) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:52:44,207] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 15:52:44,207] {logging_mixin.py:104} INFO - [2024-08-08 15:52:44,207] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:52:44,216] {logging_mixin.py:104} INFO - [2024-08-08 15:52:44,215] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 15:52:44,217] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:52:44,283] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-08 15:53:15,515] {scheduler_job.py:182} INFO - Started process (PID=54838) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:53:15,516] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 15:53:15,516] {logging_mixin.py:104} INFO - [2024-08-08 15:53:15,516] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:53:15,524] {logging_mixin.py:104} INFO - [2024-08-08 15:53:15,523] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 15:53:15,525] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 15:53:15,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 16:05:08,985] {scheduler_job.py:182} INFO - Started process (PID=54859) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:05:08,986] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 16:05:08,986] {logging_mixin.py:104} INFO - [2024-08-08 16:05:08,986] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:05:08,996] {logging_mixin.py:104} INFO - [2024-08-08 16:05:08,995] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 16:05:08,996] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:05:09,095] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.112 seconds
[2024-08-08 16:53:30,404] {scheduler_job.py:182} INFO - Started process (PID=54888) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:53:30,405] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 16:53:30,405] {logging_mixin.py:104} INFO - [2024-08-08 16:53:30,405] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:53:30,416] {logging_mixin.py:104} INFO - [2024-08-08 16:53:30,414] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 16:53:30,417] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:53:30,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-08 16:54:00,588] {scheduler_job.py:182} INFO - Started process (PID=54917) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:54:00,589] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 16:54:00,590] {logging_mixin.py:104} INFO - [2024-08-08 16:54:00,590] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:54:00,599] {logging_mixin.py:104} INFO - [2024-08-08 16:54:00,598] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 16:54:00,602] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 16:54:00,663] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-08 17:29:22,390] {scheduler_job.py:182} INFO - Started process (PID=54946) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:29:22,391] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 17:29:22,392] {logging_mixin.py:104} INFO - [2024-08-08 17:29:22,391] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:29:22,401] {logging_mixin.py:104} INFO - [2024-08-08 17:29:22,400] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 17:29:22,402] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:29:22,468] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-08 17:29:53,808] {scheduler_job.py:182} INFO - Started process (PID=54983) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:29:53,808] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 17:29:53,809] {logging_mixin.py:104} INFO - [2024-08-08 17:29:53,809] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:29:53,817] {logging_mixin.py:104} INFO - [2024-08-08 17:29:53,816] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 17:29:53,817] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:29:53,877] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 17:54:40,044] {scheduler_job.py:182} INFO - Started process (PID=55004) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:54:40,045] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 17:54:40,045] {logging_mixin.py:104} INFO - [2024-08-08 17:54:40,045] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:54:40,064] {logging_mixin.py:104} INFO - [2024-08-08 17:54:40,062] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 17:54:40,066] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:54:40,129] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.087 seconds
[2024-08-08 17:55:11,427] {scheduler_job.py:182} INFO - Started process (PID=55041) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:55:11,427] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 17:55:11,428] {logging_mixin.py:104} INFO - [2024-08-08 17:55:11,428] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:55:11,436] {logging_mixin.py:104} INFO - [2024-08-08 17:55:11,435] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 17:55:11,436] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 17:55:11,496] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 18:30:08,514] {scheduler_job.py:182} INFO - Started process (PID=55062) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:30:08,515] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 18:30:08,515] {logging_mixin.py:104} INFO - [2024-08-08 18:30:08,515] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:30:08,524] {logging_mixin.py:104} INFO - [2024-08-08 18:30:08,523] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 18:30:08,524] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:30:08,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-08 18:30:38,600] {scheduler_job.py:182} INFO - Started process (PID=55089) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:30:38,601] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 18:30:38,601] {logging_mixin.py:104} INFO - [2024-08-08 18:30:38,601] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:30:38,609] {logging_mixin.py:104} INFO - [2024-08-08 18:30:38,608] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 18:30:38,610] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:30:38,669] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 18:32:55,776] {scheduler_job.py:182} INFO - Started process (PID=55120) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:32:55,777] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 18:32:55,777] {logging_mixin.py:104} INFO - [2024-08-08 18:32:55,777] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:32:55,786] {logging_mixin.py:104} INFO - [2024-08-08 18:32:55,784] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 18:32:55,786] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:32:55,846] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 18:55:33,706] {scheduler_job.py:182} INFO - Started process (PID=55149) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:55:33,706] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 18:55:33,707] {logging_mixin.py:104} INFO - [2024-08-08 18:55:33,707] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:55:33,719] {logging_mixin.py:104} INFO - [2024-08-08 18:55:33,716] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 18:55:33,720] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:55:33,787] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2024-08-08 18:56:03,829] {scheduler_job.py:182} INFO - Started process (PID=55178) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:56:03,830] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 18:56:03,830] {logging_mixin.py:104} INFO - [2024-08-08 18:56:03,830] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:56:03,837] {logging_mixin.py:104} INFO - [2024-08-08 18:56:03,836] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 18:56:03,838] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 18:56:03,896] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.068 seconds
[2024-08-08 19:56:31,193] {scheduler_job.py:182} INFO - Started process (PID=55207) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 19:56:31,196] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 19:56:31,197] {logging_mixin.py:104} INFO - [2024-08-08 19:56:31,197] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 19:56:31,215] {logging_mixin.py:104} INFO - [2024-08-08 19:56:31,212] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 19:56:31,215] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 19:56:31,280] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.089 seconds
[2024-08-08 19:57:02,311] {scheduler_job.py:182} INFO - Started process (PID=55242) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 19:57:02,313] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 19:57:02,315] {logging_mixin.py:104} INFO - [2024-08-08 19:57:02,315] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 19:57:02,323] {logging_mixin.py:104} INFO - [2024-08-08 19:57:02,322] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 19:57:02,326] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 19:57:02,388] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-08 20:15:28,324] {scheduler_job.py:182} INFO - Started process (PID=55265) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:15:28,325] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:15:28,326] {logging_mixin.py:104} INFO - [2024-08-08 20:15:28,326] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:15:28,337] {logging_mixin.py:104} INFO - [2024-08-08 20:15:28,336] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:15:28,338] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:15:28,449] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.126 seconds
[2024-08-08 20:15:59,457] {scheduler_job.py:182} INFO - Started process (PID=55297) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:15:59,458] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:15:59,458] {logging_mixin.py:104} INFO - [2024-08-08 20:15:59,458] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:15:59,467] {logging_mixin.py:104} INFO - [2024-08-08 20:15:59,466] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:15:59,468] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:15:59,530] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 20:27:53,954] {scheduler_job.py:182} INFO - Started process (PID=55323) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:27:53,955] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:27:53,955] {logging_mixin.py:104} INFO - [2024-08-08 20:27:53,955] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:27:53,965] {logging_mixin.py:104} INFO - [2024-08-08 20:27:53,963] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:27:53,965] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:27:54,031] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2024-08-08 20:43:47,629] {scheduler_job.py:182} INFO - Started process (PID=55352) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:43:47,630] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:43:47,630] {logging_mixin.py:104} INFO - [2024-08-08 20:43:47,630] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:43:47,647] {logging_mixin.py:104} INFO - [2024-08-08 20:43:47,646] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:43:47,652] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:43:47,734] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.107 seconds
[2024-08-08 20:47:03,197] {scheduler_job.py:182} INFO - Started process (PID=55381) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:47:03,197] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:47:03,198] {logging_mixin.py:104} INFO - [2024-08-08 20:47:03,198] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:47:03,208] {logging_mixin.py:104} INFO - [2024-08-08 20:47:03,207] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:47:03,211] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:47:03,282] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.088 seconds
[2024-08-08 20:56:49,420] {scheduler_job.py:182} INFO - Started process (PID=55410) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:56:49,422] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:56:49,423] {logging_mixin.py:104} INFO - [2024-08-08 20:56:49,422] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:56:49,432] {logging_mixin.py:104} INFO - [2024-08-08 20:56:49,431] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:56:49,433] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:56:49,501] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2024-08-08 20:57:19,579] {scheduler_job.py:182} INFO - Started process (PID=55438) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:57:19,580] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:57:19,580] {logging_mixin.py:104} INFO - [2024-08-08 20:57:19,580] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:57:19,593] {logging_mixin.py:104} INFO - [2024-08-08 20:57:19,592] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:57:19,595] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:57:19,656] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2024-08-08 20:57:51,011] {scheduler_job.py:182} INFO - Started process (PID=55475) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:57:51,012] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:57:51,012] {logging_mixin.py:104} INFO - [2024-08-08 20:57:51,012] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:57:51,025] {logging_mixin.py:104} INFO - [2024-08-08 20:57:51,022] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:57:51,025] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:57:51,086] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-08 20:58:21,853] {scheduler_job.py:182} INFO - Started process (PID=55504) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:58:21,854] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:58:21,854] {logging_mixin.py:104} INFO - [2024-08-08 20:58:21,854] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:58:21,862] {logging_mixin.py:104} INFO - [2024-08-08 20:58:21,861] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:58:21,862] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:58:21,922] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 20:58:58,254] {scheduler_job.py:182} INFO - Started process (PID=55526) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:58:58,255] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:58:58,255] {logging_mixin.py:104} INFO - [2024-08-08 20:58:58,255] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:58:58,263] {logging_mixin.py:104} INFO - [2024-08-08 20:58:58,262] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:58:58,264] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:58:58,326] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 20:59:29,539] {scheduler_job.py:182} INFO - Started process (PID=55563) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:59:29,540] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 20:59:29,540] {logging_mixin.py:104} INFO - [2024-08-08 20:59:29,540] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:59:29,552] {logging_mixin.py:104} INFO - [2024-08-08 20:59:29,550] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 20:59:29,553] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 20:59:29,614] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2024-08-08 21:00:30,917] {scheduler_job.py:182} INFO - Started process (PID=55584) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:00:30,919] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:00:30,920] {logging_mixin.py:104} INFO - [2024-08-08 21:00:30,920] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:00:30,929] {logging_mixin.py:104} INFO - [2024-08-08 21:00:30,928] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:00:30,930] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:00:30,995] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-08 21:02:32,884] {scheduler_job.py:182} INFO - Started process (PID=55613) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:02:32,885] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:02:32,885] {logging_mixin.py:104} INFO - [2024-08-08 21:02:32,885] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:02:32,894] {logging_mixin.py:104} INFO - [2024-08-08 21:02:32,893] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:02:32,895] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:02:32,982] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.100 seconds
[2024-08-08 21:03:04,232] {scheduler_job.py:182} INFO - Started process (PID=55650) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:03:04,233] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:03:04,233] {logging_mixin.py:104} INFO - [2024-08-08 21:03:04,233] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:03:04,241] {logging_mixin.py:104} INFO - [2024-08-08 21:03:04,240] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:03:04,242] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:03:04,302] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 21:03:35,041] {scheduler_job.py:182} INFO - Started process (PID=55679) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:03:35,042] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:03:35,042] {logging_mixin.py:104} INFO - [2024-08-08 21:03:35,042] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:03:35,050] {logging_mixin.py:104} INFO - [2024-08-08 21:03:35,049] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:03:35,051] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:03:35,114] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 21:04:05,762] {scheduler_job.py:182} INFO - Started process (PID=55708) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:04:05,763] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:04:05,764] {logging_mixin.py:104} INFO - [2024-08-08 21:04:05,763] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:04:05,771] {logging_mixin.py:104} INFO - [2024-08-08 21:04:05,770] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:04:05,772] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:04:05,831] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 21:04:36,601] {scheduler_job.py:182} INFO - Started process (PID=55735) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:04:36,602] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:04:36,602] {logging_mixin.py:104} INFO - [2024-08-08 21:04:36,602] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:04:36,611] {logging_mixin.py:104} INFO - [2024-08-08 21:04:36,610] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:04:36,612] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:04:36,674] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 21:05:07,595] {scheduler_job.py:182} INFO - Started process (PID=55766) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:05:07,596] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:05:07,596] {logging_mixin.py:104} INFO - [2024-08-08 21:05:07,596] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:05:07,610] {logging_mixin.py:104} INFO - [2024-08-08 21:05:07,609] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:05:07,612] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:05:07,681] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.088 seconds
[2024-08-08 21:05:38,383] {scheduler_job.py:182} INFO - Started process (PID=55794) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:05:38,384] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:05:38,385] {logging_mixin.py:104} INFO - [2024-08-08 21:05:38,385] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:05:38,396] {logging_mixin.py:104} INFO - [2024-08-08 21:05:38,395] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:05:38,400] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:05:38,466] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2024-08-08 21:06:09,095] {scheduler_job.py:182} INFO - Started process (PID=55822) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:06:09,095] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:06:09,096] {logging_mixin.py:104} INFO - [2024-08-08 21:06:09,096] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:06:09,105] {logging_mixin.py:104} INFO - [2024-08-08 21:06:09,104] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:06:09,106] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:06:09,168] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 21:06:40,016] {scheduler_job.py:182} INFO - Started process (PID=55851) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:06:40,017] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:06:40,017] {logging_mixin.py:104} INFO - [2024-08-08 21:06:40,017] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:06:40,025] {logging_mixin.py:104} INFO - [2024-08-08 21:06:40,024] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:06:40,026] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:06:40,086] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 21:07:10,802] {scheduler_job.py:182} INFO - Started process (PID=55880) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:07:10,803] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:07:10,805] {logging_mixin.py:104} INFO - [2024-08-08 21:07:10,805] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:07:10,814] {logging_mixin.py:104} INFO - [2024-08-08 21:07:10,813] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:07:10,814] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:07:10,876] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-08 21:07:41,645] {scheduler_job.py:182} INFO - Started process (PID=55909) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:07:41,645] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:07:41,646] {logging_mixin.py:104} INFO - [2024-08-08 21:07:41,646] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:07:41,654] {logging_mixin.py:104} INFO - [2024-08-08 21:07:41,653] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:07:41,658] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:07:41,719] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-08 21:08:12,517] {scheduler_job.py:182} INFO - Started process (PID=55939) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:08:12,518] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:08:12,518] {logging_mixin.py:104} INFO - [2024-08-08 21:08:12,518] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:08:12,527] {logging_mixin.py:104} INFO - [2024-08-08 21:08:12,526] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:08:12,528] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:08:12,588] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 21:08:43,359] {scheduler_job.py:182} INFO - Started process (PID=55967) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:08:43,360] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:08:43,361] {logging_mixin.py:104} INFO - [2024-08-08 21:08:43,361] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:08:43,372] {logging_mixin.py:104} INFO - [2024-08-08 21:08:43,369] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:08:43,374] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:08:43,437] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2024-08-08 21:09:14,319] {scheduler_job.py:182} INFO - Started process (PID=55998) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:09:14,321] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:09:14,322] {logging_mixin.py:104} INFO - [2024-08-08 21:09:14,322] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:09:14,331] {logging_mixin.py:104} INFO - [2024-08-08 21:09:14,330] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:09:14,332] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:09:14,392] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 21:09:44,876] {scheduler_job.py:182} INFO - Started process (PID=56024) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:09:44,877] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:09:44,877] {logging_mixin.py:104} INFO - [2024-08-08 21:09:44,877] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:09:44,886] {logging_mixin.py:104} INFO - [2024-08-08 21:09:44,885] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:09:44,886] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:09:44,948] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2024-08-08 21:10:15,633] {scheduler_job.py:182} INFO - Started process (PID=56053) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:10:15,634] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:10:15,634] {logging_mixin.py:104} INFO - [2024-08-08 21:10:15,634] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:10:15,642] {logging_mixin.py:104} INFO - [2024-08-08 21:10:15,641] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:10:15,643] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:10:15,703] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 21:10:46,710] {scheduler_job.py:182} INFO - Started process (PID=56085) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:10:46,711] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:10:46,711] {logging_mixin.py:104} INFO - [2024-08-08 21:10:46,711] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:10:46,719] {logging_mixin.py:104} INFO - [2024-08-08 21:10:46,718] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:10:46,720] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:10:46,781] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 21:11:17,368] {scheduler_job.py:182} INFO - Started process (PID=56113) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:11:17,369] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:11:17,369] {logging_mixin.py:104} INFO - [2024-08-08 21:11:17,369] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:11:17,378] {logging_mixin.py:104} INFO - [2024-08-08 21:11:17,377] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:11:17,379] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:11:17,439] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.073 seconds
[2024-08-08 21:11:48,159] {scheduler_job.py:182} INFO - Started process (PID=56142) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:11:48,160] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:11:48,160] {logging_mixin.py:104} INFO - [2024-08-08 21:11:48,160] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:11:48,169] {logging_mixin.py:104} INFO - [2024-08-08 21:11:48,168] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:11:48,169] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:11:48,228] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.071 seconds
[2024-08-08 21:12:18,893] {scheduler_job.py:182} INFO - Started process (PID=56170) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:12:18,894] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:12:18,894] {logging_mixin.py:104} INFO - [2024-08-08 21:12:18,894] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:12:18,902] {logging_mixin.py:104} INFO - [2024-08-08 21:12:18,901] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:12:18,902] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:12:18,962] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 21:14:16,211] {scheduler_job.py:182} INFO - Started process (PID=56193) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:14:16,212] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 21:14:16,212] {logging_mixin.py:104} INFO - [2024-08-08 21:14:16,212] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:14:16,223] {logging_mixin.py:104} INFO - [2024-08-08 21:14:16,220] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 21:14:16,225] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 21:14:16,285] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2024-08-08 22:02:58,497] {scheduler_job.py:182} INFO - Started process (PID=56222) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:02:58,498] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 22:02:58,499] {logging_mixin.py:104} INFO - [2024-08-08 22:02:58,499] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:02:58,507] {logging_mixin.py:104} INFO - [2024-08-08 22:02:58,506] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 22:02:58,508] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:02:58,567] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 22:03:29,519] {scheduler_job.py:182} INFO - Started process (PID=56250) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:03:29,520] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 22:03:29,521] {logging_mixin.py:104} INFO - [2024-08-08 22:03:29,521] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:03:29,532] {logging_mixin.py:104} INFO - [2024-08-08 22:03:29,530] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 22:03:29,533] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:03:29,592] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2024-08-08 22:54:10,217] {scheduler_job.py:182} INFO - Started process (PID=56280) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:54:10,218] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 22:54:10,220] {logging_mixin.py:104} INFO - [2024-08-08 22:54:10,220] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:54:10,233] {logging_mixin.py:104} INFO - [2024-08-08 22:54:10,231] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 22:54:10,235] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 22:54:10,310] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.096 seconds
[2024-08-08 23:13:19,120] {scheduler_job.py:182} INFO - Started process (PID=56309) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 23:13:19,121] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 23:13:19,121] {logging_mixin.py:104} INFO - [2024-08-08 23:13:19,121] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 23:13:19,129] {logging_mixin.py:104} INFO - [2024-08-08 23:13:19,128] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 23:13:19,130] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 23:13:19,190] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2024-08-08 23:29:48,423] {scheduler_job.py:182} INFO - Started process (PID=56338) to work on /opt/airflow/dags/create_demo_table.py
[2024-08-08 23:29:48,424] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2024-08-08 23:29:48,424] {logging_mixin.py:104} INFO - [2024-08-08 23:29:48,424] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2024-08-08 23:29:48,436] {logging_mixin.py:104} INFO - [2024-08-08 23:29:48,435] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2024-08-08 23:29:48,437] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2024-08-08 23:29:48,510] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.089 seconds
