[2025-02-11 15:21:29,148] {scheduler_job.py:182} INFO - Started process (PID=48) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:21:29,149] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:21:29,149] {logging_mixin.py:104} INFO - [2025-02-11 15:21:29,149] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:21:29,164] {logging_mixin.py:104} INFO - [2025-02-11 15:21:29,162] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:21:29,166] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:21:29,248] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.103 seconds
[2025-02-11 15:22:00,154] {scheduler_job.py:182} INFO - Started process (PID=78) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:22:00,154] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:22:00,155] {logging_mixin.py:104} INFO - [2025-02-11 15:22:00,154] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:22:00,164] {logging_mixin.py:104} INFO - [2025-02-11 15:22:00,162] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:22:00,165] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:22:00,239] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.087 seconds
[2025-02-11 15:22:30,581] {scheduler_job.py:182} INFO - Started process (PID=98) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:22:30,581] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:22:30,581] {logging_mixin.py:104} INFO - [2025-02-11 15:22:30,581] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:22:30,589] {logging_mixin.py:104} INFO - [2025-02-11 15:22:30,588] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:22:30,590] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:22:30,657] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:23:01,627] {scheduler_job.py:182} INFO - Started process (PID=127) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:23:01,628] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:23:01,628] {logging_mixin.py:104} INFO - [2025-02-11 15:23:01,628] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:23:01,636] {logging_mixin.py:104} INFO - [2025-02-11 15:23:01,635] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:23:01,636] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:23:01,699] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.074 seconds
[2025-02-11 15:23:32,546] {scheduler_job.py:182} INFO - Started process (PID=156) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:23:32,546] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:23:32,547] {logging_mixin.py:104} INFO - [2025-02-11 15:23:32,547] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:23:32,555] {logging_mixin.py:104} INFO - [2025-02-11 15:23:32,554] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:23:32,555] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:23:32,627] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2025-02-11 15:24:03,260] {scheduler_job.py:182} INFO - Started process (PID=184) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:24:03,260] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:24:03,261] {logging_mixin.py:104} INFO - [2025-02-11 15:24:03,261] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:24:03,269] {logging_mixin.py:104} INFO - [2025-02-11 15:24:03,268] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:24:03,269] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:24:03,335] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:24:33,999] {scheduler_job.py:182} INFO - Started process (PID=213) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:24:34,000] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:24:34,000] {logging_mixin.py:104} INFO - [2025-02-11 15:24:34,000] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:24:34,009] {logging_mixin.py:104} INFO - [2025-02-11 15:24:34,008] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:24:34,013] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:24:34,078] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2025-02-11 15:25:04,838] {scheduler_job.py:182} INFO - Started process (PID=242) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:25:04,839] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:25:04,839] {logging_mixin.py:104} INFO - [2025-02-11 15:25:04,839] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:25:04,847] {logging_mixin.py:104} INFO - [2025-02-11 15:25:04,846] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:25:04,848] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:25:04,913] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:25:35,631] {scheduler_job.py:182} INFO - Started process (PID=271) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:25:35,631] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:25:35,632] {logging_mixin.py:104} INFO - [2025-02-11 15:25:35,632] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:25:35,642] {logging_mixin.py:104} INFO - [2025-02-11 15:25:35,640] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:25:35,642] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:25:35,708] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2025-02-11 15:26:06,469] {scheduler_job.py:182} INFO - Started process (PID=300) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:26:06,470] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:26:06,470] {logging_mixin.py:104} INFO - [2025-02-11 15:26:06,470] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:26:06,482] {logging_mixin.py:104} INFO - [2025-02-11 15:26:06,481] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:26:06,483] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:26:06,547] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2025-02-11 15:26:37,349] {scheduler_job.py:182} INFO - Started process (PID=329) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:26:37,349] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:26:37,350] {logging_mixin.py:104} INFO - [2025-02-11 15:26:37,350] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:26:37,359] {logging_mixin.py:104} INFO - [2025-02-11 15:26:37,358] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:26:37,360] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:26:37,426] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:27:08,151] {scheduler_job.py:182} INFO - Started process (PID=358) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:27:08,151] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:27:08,151] {logging_mixin.py:104} INFO - [2025-02-11 15:27:08,151] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:27:08,160] {logging_mixin.py:104} INFO - [2025-02-11 15:27:08,159] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:27:08,160] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:27:08,224] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2025-02-11 15:27:38,958] {scheduler_job.py:182} INFO - Started process (PID=387) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:27:38,959] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:27:38,959] {logging_mixin.py:104} INFO - [2025-02-11 15:27:38,959] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:27:38,968] {logging_mixin.py:104} INFO - [2025-02-11 15:27:38,967] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:27:38,969] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:27:39,033] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 15:28:09,723] {scheduler_job.py:182} INFO - Started process (PID=416) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:28:09,724] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:28:09,725] {logging_mixin.py:104} INFO - [2025-02-11 15:28:09,725] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:28:09,733] {logging_mixin.py:104} INFO - [2025-02-11 15:28:09,732] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:28:09,733] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:28:09,798] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 15:28:40,506] {scheduler_job.py:182} INFO - Started process (PID=445) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:28:40,507] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:28:40,507] {logging_mixin.py:104} INFO - [2025-02-11 15:28:40,507] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:28:40,518] {logging_mixin.py:104} INFO - [2025-02-11 15:28:40,517] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:28:40,519] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:28:40,583] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:29:11,348] {scheduler_job.py:182} INFO - Started process (PID=474) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:29:11,349] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:29:11,350] {logging_mixin.py:104} INFO - [2025-02-11 15:29:11,349] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:29:11,361] {logging_mixin.py:104} INFO - [2025-02-11 15:29:11,360] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:29:11,362] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:29:11,431] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2025-02-11 15:29:42,319] {scheduler_job.py:182} INFO - Started process (PID=503) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:29:42,319] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:29:42,320] {logging_mixin.py:104} INFO - [2025-02-11 15:29:42,320] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:29:42,329] {logging_mixin.py:104} INFO - [2025-02-11 15:29:42,328] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:29:42,330] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:29:42,399] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2025-02-11 15:30:13,251] {scheduler_job.py:182} INFO - Started process (PID=532) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:30:13,252] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:30:13,252] {logging_mixin.py:104} INFO - [2025-02-11 15:30:13,252] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:30:13,261] {logging_mixin.py:104} INFO - [2025-02-11 15:30:13,260] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:30:13,261] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:30:13,326] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 15:30:44,089] {scheduler_job.py:182} INFO - Started process (PID=561) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:30:44,089] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:30:44,090] {logging_mixin.py:104} INFO - [2025-02-11 15:30:44,090] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:30:44,098] {logging_mixin.py:104} INFO - [2025-02-11 15:30:44,097] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:30:44,099] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:30:44,163] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 15:31:14,914] {scheduler_job.py:182} INFO - Started process (PID=590) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:31:14,914] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:31:14,915] {logging_mixin.py:104} INFO - [2025-02-11 15:31:14,915] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:31:14,923] {logging_mixin.py:104} INFO - [2025-02-11 15:31:14,922] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:31:14,924] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:31:14,987] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2025-02-11 15:31:45,785] {scheduler_job.py:182} INFO - Started process (PID=619) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:31:45,785] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:31:45,786] {logging_mixin.py:104} INFO - [2025-02-11 15:31:45,785] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:31:45,794] {logging_mixin.py:104} INFO - [2025-02-11 15:31:45,793] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:31:45,794] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:31:45,859] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 15:32:16,610] {scheduler_job.py:182} INFO - Started process (PID=648) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:32:16,610] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:32:16,612] {logging_mixin.py:104} INFO - [2025-02-11 15:32:16,612] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:32:16,620] {logging_mixin.py:104} INFO - [2025-02-11 15:32:16,619] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:32:16,621] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:32:16,686] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:32:47,471] {scheduler_job.py:182} INFO - Started process (PID=677) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:32:47,471] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:32:47,472] {logging_mixin.py:104} INFO - [2025-02-11 15:32:47,472] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:32:47,483] {logging_mixin.py:104} INFO - [2025-02-11 15:32:47,482] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:32:47,483] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:32:47,550] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2025-02-11 15:33:18,298] {scheduler_job.py:182} INFO - Started process (PID=706) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:33:18,299] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:33:18,300] {logging_mixin.py:104} INFO - [2025-02-11 15:33:18,299] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:33:18,307] {logging_mixin.py:104} INFO - [2025-02-11 15:33:18,306] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:33:18,308] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:33:18,374] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:33:49,088] {scheduler_job.py:182} INFO - Started process (PID=735) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:33:49,089] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:33:49,090] {logging_mixin.py:104} INFO - [2025-02-11 15:33:49,090] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:33:49,097] {logging_mixin.py:104} INFO - [2025-02-11 15:33:49,096] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:33:49,098] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:33:49,162] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2025-02-11 15:34:19,907] {scheduler_job.py:182} INFO - Started process (PID=764) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:34:19,907] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:34:19,907] {logging_mixin.py:104} INFO - [2025-02-11 15:34:19,907] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:34:19,915] {logging_mixin.py:104} INFO - [2025-02-11 15:34:19,914] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:34:19,917] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:34:19,982] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:34:50,728] {scheduler_job.py:182} INFO - Started process (PID=793) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:34:50,728] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:34:50,729] {logging_mixin.py:104} INFO - [2025-02-11 15:34:50,729] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:34:50,736] {logging_mixin.py:104} INFO - [2025-02-11 15:34:50,736] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:34:50,737] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:34:50,803] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:35:21,502] {scheduler_job.py:182} INFO - Started process (PID=822) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:35:21,502] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:35:21,502] {logging_mixin.py:104} INFO - [2025-02-11 15:35:21,502] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:35:21,512] {logging_mixin.py:104} INFO - [2025-02-11 15:35:21,511] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:35:21,513] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:35:21,580] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2025-02-11 15:35:52,322] {scheduler_job.py:182} INFO - Started process (PID=851) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:35:52,323] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:35:52,323] {logging_mixin.py:104} INFO - [2025-02-11 15:35:52,323] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:35:52,332] {logging_mixin.py:104} INFO - [2025-02-11 15:35:52,331] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:35:52,332] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:35:52,399] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:36:23,158] {scheduler_job.py:182} INFO - Started process (PID=880) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:36:23,159] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:36:23,159] {logging_mixin.py:104} INFO - [2025-02-11 15:36:23,159] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:36:23,169] {logging_mixin.py:104} INFO - [2025-02-11 15:36:23,168] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:36:23,169] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:36:23,233] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 15:36:54,021] {scheduler_job.py:182} INFO - Started process (PID=909) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:36:54,022] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:36:54,022] {logging_mixin.py:104} INFO - [2025-02-11 15:36:54,022] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:36:54,033] {logging_mixin.py:104} INFO - [2025-02-11 15:36:54,032] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:36:54,034] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:36:54,101] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2025-02-11 15:37:24,851] {scheduler_job.py:182} INFO - Started process (PID=938) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:37:24,852] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:37:24,852] {logging_mixin.py:104} INFO - [2025-02-11 15:37:24,852] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:37:24,865] {logging_mixin.py:104} INFO - [2025-02-11 15:37:24,864] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:37:24,865] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:37:24,932] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2025-02-11 15:37:55,648] {scheduler_job.py:182} INFO - Started process (PID=967) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:37:55,649] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:37:55,649] {logging_mixin.py:104} INFO - [2025-02-11 15:37:55,649] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:37:55,659] {logging_mixin.py:104} INFO - [2025-02-11 15:37:55,658] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:37:55,660] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:37:55,726] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2025-02-11 15:38:26,509] {scheduler_job.py:182} INFO - Started process (PID=996) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:38:26,512] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:38:26,512] {logging_mixin.py:104} INFO - [2025-02-11 15:38:26,512] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:38:26,520] {logging_mixin.py:104} INFO - [2025-02-11 15:38:26,519] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:38:26,521] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:38:26,587] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2025-02-11 15:38:57,410] {scheduler_job.py:182} INFO - Started process (PID=1025) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:38:57,411] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:38:57,414] {logging_mixin.py:104} INFO - [2025-02-11 15:38:57,414] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:38:57,427] {logging_mixin.py:104} INFO - [2025-02-11 15:38:57,426] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:38:57,428] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:38:57,499] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.091 seconds
[2025-02-11 15:39:28,296] {scheduler_job.py:182} INFO - Started process (PID=1054) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:39:28,297] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:39:28,297] {logging_mixin.py:104} INFO - [2025-02-11 15:39:28,297] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:39:28,308] {logging_mixin.py:104} INFO - [2025-02-11 15:39:28,307] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:39:28,308] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:39:28,373] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:39:59,139] {scheduler_job.py:182} INFO - Started process (PID=1083) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:39:59,140] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:39:59,141] {logging_mixin.py:104} INFO - [2025-02-11 15:39:59,141] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:39:59,149] {logging_mixin.py:104} INFO - [2025-02-11 15:39:59,148] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:39:59,150] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:39:59,215] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:40:29,922] {scheduler_job.py:182} INFO - Started process (PID=1112) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:40:29,922] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:40:29,923] {logging_mixin.py:104} INFO - [2025-02-11 15:40:29,923] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:40:29,931] {logging_mixin.py:104} INFO - [2025-02-11 15:40:29,930] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:40:29,932] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:40:29,996] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2025-02-11 15:41:00,735] {scheduler_job.py:182} INFO - Started process (PID=1141) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:41:00,736] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:41:00,736] {logging_mixin.py:104} INFO - [2025-02-11 15:41:00,736] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:41:00,744] {logging_mixin.py:104} INFO - [2025-02-11 15:41:00,743] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:41:00,745] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:41:00,809] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2025-02-11 15:41:31,577] {scheduler_job.py:182} INFO - Started process (PID=1170) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:41:31,578] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:41:31,578] {logging_mixin.py:104} INFO - [2025-02-11 15:41:31,578] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:41:31,589] {logging_mixin.py:104} INFO - [2025-02-11 15:41:31,588] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:41:31,590] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:41:31,661] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.086 seconds
[2025-02-11 15:42:02,549] {scheduler_job.py:182} INFO - Started process (PID=1199) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:42:02,550] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:42:02,550] {logging_mixin.py:104} INFO - [2025-02-11 15:42:02,550] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:42:02,558] {logging_mixin.py:104} INFO - [2025-02-11 15:42:02,557] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:42:02,559] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:42:02,625] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:42:33,355] {scheduler_job.py:182} INFO - Started process (PID=1228) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:42:33,356] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:42:33,358] {logging_mixin.py:104} INFO - [2025-02-11 15:42:33,358] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:42:33,367] {logging_mixin.py:104} INFO - [2025-02-11 15:42:33,366] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:42:33,368] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:42:33,433] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2025-02-11 15:43:04,193] {scheduler_job.py:182} INFO - Started process (PID=1257) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:43:04,193] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:43:04,194] {logging_mixin.py:104} INFO - [2025-02-11 15:43:04,194] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:43:04,202] {logging_mixin.py:104} INFO - [2025-02-11 15:43:04,201] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:43:04,202] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:43:04,268] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:43:35,039] {scheduler_job.py:182} INFO - Started process (PID=1286) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:43:35,040] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:43:35,042] {logging_mixin.py:104} INFO - [2025-02-11 15:43:35,042] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:43:35,050] {logging_mixin.py:104} INFO - [2025-02-11 15:43:35,049] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:43:35,050] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:43:35,117] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2025-02-11 15:44:05,891] {scheduler_job.py:182} INFO - Started process (PID=1315) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:44:05,892] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:44:05,893] {logging_mixin.py:104} INFO - [2025-02-11 15:44:05,893] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:44:05,901] {logging_mixin.py:104} INFO - [2025-02-11 15:44:05,900] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:44:05,901] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:44:05,967] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:44:36,734] {scheduler_job.py:182} INFO - Started process (PID=1344) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:44:36,734] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:44:36,735] {logging_mixin.py:104} INFO - [2025-02-11 15:44:36,735] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:44:36,744] {logging_mixin.py:104} INFO - [2025-02-11 15:44:36,743] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:44:36,745] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:44:36,812] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2025-02-11 15:45:07,553] {scheduler_job.py:182} INFO - Started process (PID=1373) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:45:07,553] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:45:07,554] {logging_mixin.py:104} INFO - [2025-02-11 15:45:07,554] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:45:07,562] {logging_mixin.py:104} INFO - [2025-02-11 15:45:07,561] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:45:07,562] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:45:07,626] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2025-02-11 15:45:38,381] {scheduler_job.py:182} INFO - Started process (PID=1402) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:45:38,382] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:45:38,382] {logging_mixin.py:104} INFO - [2025-02-11 15:45:38,382] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:45:38,390] {logging_mixin.py:104} INFO - [2025-02-11 15:45:38,389] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:45:38,391] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:45:38,456] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:46:09,245] {scheduler_job.py:182} INFO - Started process (PID=1431) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:46:09,246] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:46:09,246] {logging_mixin.py:104} INFO - [2025-02-11 15:46:09,246] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:46:09,255] {logging_mixin.py:104} INFO - [2025-02-11 15:46:09,254] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:46:09,256] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:46:09,323] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2025-02-11 15:46:40,210] {scheduler_job.py:182} INFO - Started process (PID=1460) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:46:40,210] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:46:40,211] {logging_mixin.py:104} INFO - [2025-02-11 15:46:40,211] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:46:40,219] {logging_mixin.py:104} INFO - [2025-02-11 15:46:40,218] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:46:40,219] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:46:40,286] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.078 seconds
[2025-02-11 15:47:11,150] {scheduler_job.py:182} INFO - Started process (PID=1489) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:47:11,150] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:47:11,151] {logging_mixin.py:104} INFO - [2025-02-11 15:47:11,151] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:47:11,164] {logging_mixin.py:104} INFO - [2025-02-11 15:47:11,162] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:47:11,165] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:47:11,249] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.101 seconds
[2025-02-11 15:47:42,116] {scheduler_job.py:182} INFO - Started process (PID=1518) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:47:42,117] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:47:42,117] {logging_mixin.py:104} INFO - [2025-02-11 15:47:42,117] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:47:42,126] {logging_mixin.py:104} INFO - [2025-02-11 15:47:42,125] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:47:42,126] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:47:42,191] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:48:12,925] {scheduler_job.py:182} INFO - Started process (PID=1547) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:48:12,926] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:48:12,926] {logging_mixin.py:104} INFO - [2025-02-11 15:48:12,926] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:48:12,934] {logging_mixin.py:104} INFO - [2025-02-11 15:48:12,933] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:48:12,935] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:48:12,999] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 15:48:43,852] {scheduler_job.py:182} INFO - Started process (PID=1576) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:48:43,853] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:48:43,853] {logging_mixin.py:104} INFO - [2025-02-11 15:48:43,853] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:48:43,861] {logging_mixin.py:104} INFO - [2025-02-11 15:48:43,860] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:48:43,861] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:48:43,927] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:49:14,709] {scheduler_job.py:182} INFO - Started process (PID=1605) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:49:14,710] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:49:14,710] {logging_mixin.py:104} INFO - [2025-02-11 15:49:14,710] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:49:14,719] {logging_mixin.py:104} INFO - [2025-02-11 15:49:14,718] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:49:14,720] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:49:14,788] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
[2025-02-11 15:49:45,556] {scheduler_job.py:182} INFO - Started process (PID=1634) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:49:45,556] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:49:45,557] {logging_mixin.py:104} INFO - [2025-02-11 15:49:45,557] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:49:45,564] {logging_mixin.py:104} INFO - [2025-02-11 15:49:45,564] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:49:45,565] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:49:45,630] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.075 seconds
[2025-02-11 15:50:16,399] {scheduler_job.py:182} INFO - Started process (PID=1663) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:50:16,399] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:50:16,400] {logging_mixin.py:104} INFO - [2025-02-11 15:50:16,400] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:50:16,410] {logging_mixin.py:104} INFO - [2025-02-11 15:50:16,409] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:50:16,411] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:50:16,479] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2025-02-11 15:50:47,250] {scheduler_job.py:182} INFO - Started process (PID=1692) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:50:47,251] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:50:47,251] {logging_mixin.py:104} INFO - [2025-02-11 15:50:47,251] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:50:47,260] {logging_mixin.py:104} INFO - [2025-02-11 15:50:47,259] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:50:47,261] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:50:47,330] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2025-02-11 15:51:18,592] {scheduler_job.py:182} INFO - Started process (PID=1726) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:51:18,593] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:51:18,593] {logging_mixin.py:104} INFO - [2025-02-11 15:51:18,593] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:51:18,602] {logging_mixin.py:104} INFO - [2025-02-11 15:51:18,601] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:51:18,602] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:51:18,668] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 15:51:49,559] {scheduler_job.py:182} INFO - Started process (PID=1756) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:51:49,559] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:51:49,560] {logging_mixin.py:104} INFO - [2025-02-11 15:51:49,559] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:51:49,568] {logging_mixin.py:104} INFO - [2025-02-11 15:51:49,567] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:51:49,568] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:51:49,658] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.102 seconds
[2025-02-11 15:52:52,079] {scheduler_job.py:182} INFO - Started process (PID=36) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:52:52,082] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:52:52,091] {logging_mixin.py:104} INFO - [2025-02-11 15:52:52,091] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:52:52,114] {logging_mixin.py:104} INFO - [2025-02-11 15:52:52,113] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:52:52,116] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:52:52,190] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.114 seconds
[2025-02-11 15:53:22,655] {scheduler_job.py:182} INFO - Started process (PID=66) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:53:22,656] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:53:22,656] {logging_mixin.py:104} INFO - [2025-02-11 15:53:22,656] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:53:22,668] {logging_mixin.py:104} INFO - [2025-02-11 15:53:22,666] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:53:22,668] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:53:22,740] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.088 seconds
[2025-02-11 15:53:53,102] {scheduler_job.py:182} INFO - Started process (PID=96) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:53:53,103] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:53:53,104] {logging_mixin.py:104} INFO - [2025-02-11 15:53:53,103] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:53:53,115] {logging_mixin.py:104} INFO - [2025-02-11 15:53:53,113] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:53:53,117] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:53:53,188] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.088 seconds
[2025-02-11 15:54:23,536] {scheduler_job.py:182} INFO - Started process (PID=127) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:54:23,537] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:54:23,537] {logging_mixin.py:104} INFO - [2025-02-11 15:54:23,537] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:54:23,546] {logging_mixin.py:104} INFO - [2025-02-11 15:54:23,545] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:54:23,547] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:54:23,616] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.082 seconds
[2025-02-11 15:54:53,711] {scheduler_job.py:182} INFO - Started process (PID=157) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:54:53,711] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:54:53,712] {logging_mixin.py:104} INFO - [2025-02-11 15:54:53,712] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:54:53,719] {logging_mixin.py:104} INFO - [2025-02-11 15:54:53,718] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:54:53,720] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:54:53,782] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2025-02-11 15:55:23,858] {scheduler_job.py:182} INFO - Started process (PID=187) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:55:23,858] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:55:23,859] {logging_mixin.py:104} INFO - [2025-02-11 15:55:23,859] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:55:23,866] {logging_mixin.py:104} INFO - [2025-02-11 15:55:23,865] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:55:23,866] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:55:23,928] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.072 seconds
[2025-02-11 15:55:53,942] {scheduler_job.py:182} INFO - Started process (PID=217) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:55:53,942] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:55:53,943] {logging_mixin.py:104} INFO - [2025-02-11 15:55:53,943] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:55:53,954] {logging_mixin.py:104} INFO - [2025-02-11 15:55:53,953] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:55:53,954] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:55:54,019] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2025-02-11 15:56:24,330] {scheduler_job.py:182} INFO - Started process (PID=248) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:56:24,331] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:56:24,332] {logging_mixin.py:104} INFO - [2025-02-11 15:56:24,332] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:56:24,341] {logging_mixin.py:104} INFO - [2025-02-11 15:56:24,340] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:56:24,341] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:56:24,415] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.086 seconds
[2025-02-11 15:56:54,447] {scheduler_job.py:182} INFO - Started process (PID=278) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:56:54,448] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:56:54,448] {logging_mixin.py:104} INFO - [2025-02-11 15:56:54,448] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:56:54,458] {logging_mixin.py:104} INFO - [2025-02-11 15:56:54,457] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:56:54,458] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:56:54,526] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2025-02-11 15:57:25,290] {scheduler_job.py:182} INFO - Started process (PID=306) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:57:25,291] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:57:25,294] {logging_mixin.py:104} INFO - [2025-02-11 15:57:25,294] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:57:25,306] {logging_mixin.py:104} INFO - [2025-02-11 15:57:25,305] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:57:25,307] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:57:25,375] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.086 seconds
[2025-02-11 15:57:56,298] {scheduler_job.py:182} INFO - Started process (PID=336) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:57:56,299] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:57:56,299] {logging_mixin.py:104} INFO - [2025-02-11 15:57:56,299] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:57:56,309] {logging_mixin.py:104} INFO - [2025-02-11 15:57:56,308] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:57:56,309] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:57:56,377] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.081 seconds
[2025-02-11 15:58:27,281] {scheduler_job.py:182} INFO - Started process (PID=365) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:58:27,282] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:58:27,284] {logging_mixin.py:104} INFO - [2025-02-11 15:58:27,284] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:58:27,298] {logging_mixin.py:104} INFO - [2025-02-11 15:58:27,297] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:58:27,299] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:58:27,368] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.089 seconds
[2025-02-11 15:58:58,393] {scheduler_job.py:182} INFO - Started process (PID=394) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:58:58,394] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:58:58,397] {logging_mixin.py:104} INFO - [2025-02-11 15:58:58,397] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:58:58,408] {logging_mixin.py:104} INFO - [2025-02-11 15:58:58,407] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:58:58,409] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:58:58,477] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2025-02-11 15:59:29,483] {scheduler_job.py:182} INFO - Started process (PID=423) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:59:29,483] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 15:59:29,484] {logging_mixin.py:104} INFO - [2025-02-11 15:59:29,484] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:59:29,495] {logging_mixin.py:104} INFO - [2025-02-11 15:59:29,494] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 15:59:29,496] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 15:59:29,566] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.085 seconds
[2025-02-11 16:00:00,597] {scheduler_job.py:182} INFO - Started process (PID=452) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:00:00,601] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:00:00,602] {logging_mixin.py:104} INFO - [2025-02-11 16:00:00,602] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:00:00,615] {logging_mixin.py:104} INFO - [2025-02-11 16:00:00,609] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:00:00,621] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:00:00,692] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.097 seconds
[2025-02-11 16:00:30,793] {scheduler_job.py:182} INFO - Started process (PID=482) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:00:30,793] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:00:30,794] {logging_mixin.py:104} INFO - [2025-02-11 16:00:30,794] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:00:30,802] {logging_mixin.py:104} INFO - [2025-02-11 16:00:30,801] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:00:30,802] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:00:30,868] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 16:01:01,711] {scheduler_job.py:182} INFO - Started process (PID=511) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:01:01,711] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:01:01,712] {logging_mixin.py:104} INFO - [2025-02-11 16:01:01,712] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:01:01,720] {logging_mixin.py:104} INFO - [2025-02-11 16:01:01,719] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:01:01,720] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:01:01,786] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 16:01:32,598] {scheduler_job.py:182} INFO - Started process (PID=540) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:01:32,599] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:01:32,599] {logging_mixin.py:104} INFO - [2025-02-11 16:01:32,599] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:01:32,608] {logging_mixin.py:104} INFO - [2025-02-11 16:01:32,607] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:01:32,608] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:01:32,673] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 16:02:03,518] {scheduler_job.py:182} INFO - Started process (PID=569) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:02:03,518] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:02:03,519] {logging_mixin.py:104} INFO - [2025-02-11 16:02:03,519] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:02:03,528] {logging_mixin.py:104} INFO - [2025-02-11 16:02:03,527] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:02:03,529] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:02:03,610] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.095 seconds
[2025-02-11 16:02:34,522] {scheduler_job.py:182} INFO - Started process (PID=598) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:02:34,522] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:02:34,523] {logging_mixin.py:104} INFO - [2025-02-11 16:02:34,523] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:02:34,534] {logging_mixin.py:104} INFO - [2025-02-11 16:02:34,533] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:02:34,535] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:02:34,609] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.091 seconds
[2025-02-11 16:03:05,469] {scheduler_job.py:182} INFO - Started process (PID=627) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:03:05,470] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:03:05,470] {logging_mixin.py:104} INFO - [2025-02-11 16:03:05,470] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:03:05,478] {logging_mixin.py:104} INFO - [2025-02-11 16:03:05,477] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:03:05,479] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:03:05,545] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 16:03:36,312] {scheduler_job.py:182} INFO - Started process (PID=656) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:03:36,312] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:03:36,313] {logging_mixin.py:104} INFO - [2025-02-11 16:03:36,313] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:03:36,321] {logging_mixin.py:104} INFO - [2025-02-11 16:03:36,320] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:03:36,321] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:03:36,389] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.079 seconds
[2025-02-11 16:04:07,109] {scheduler_job.py:182} INFO - Started process (PID=685) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:04:07,110] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:04:07,110] {logging_mixin.py:104} INFO - [2025-02-11 16:04:07,110] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:04:07,118] {logging_mixin.py:104} INFO - [2025-02-11 16:04:07,117] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:04:07,119] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:04:07,185] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 16:04:38,100] {scheduler_job.py:182} INFO - Started process (PID=714) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:04:38,101] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:04:38,101] {logging_mixin.py:104} INFO - [2025-02-11 16:04:38,101] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:04:38,110] {logging_mixin.py:104} INFO - [2025-02-11 16:04:38,109] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:04:38,110] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:04:38,176] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.077 seconds
[2025-02-11 16:05:08,863] {scheduler_job.py:182} INFO - Started process (PID=743) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:05:08,864] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:05:08,864] {logging_mixin.py:104} INFO - [2025-02-11 16:05:08,864] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:05:08,871] {logging_mixin.py:104} INFO - [2025-02-11 16:05:08,871] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:05:08,872] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:05:08,937] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.076 seconds
[2025-02-11 16:05:39,821] {scheduler_job.py:182} INFO - Started process (PID=772) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:05:39,822] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:05:39,823] {logging_mixin.py:104} INFO - [2025-02-11 16:05:39,823] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:05:39,833] {logging_mixin.py:104} INFO - [2025-02-11 16:05:39,832] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:05:39,834] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:05:39,902] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.083 seconds
[2025-02-11 16:06:10,894] {scheduler_job.py:182} INFO - Started process (PID=801) to work on /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:06:10,894] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/create_demo_table.py for tasks to queue
[2025-02-11 16:06:10,895] {logging_mixin.py:104} INFO - [2025-02-11 16:06:10,895] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:06:10,904] {logging_mixin.py:104} INFO - [2025-02-11 16:06:10,903] {dagbag.py:308} ERROR - Failed to import: /opt/airflow/dags/create_demo_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_demo_table.py", line 8, in <module>
    from airflow.operators.sql import SQLExecuteQueryOperator
ImportError: cannot import name 'SQLExecuteQueryOperator'
[2025-02-11 16:06:10,904] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/create_demo_table.py
[2025-02-11 16:06:10,972] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/create_demo_table.py took 0.080 seconds
